Doxygen Fortran Example: general.RK6.f File Reference
general.RK6.f File Reference
Functions/Subroutines
program test
subroutine INIT (uvec, uexact, dt, iDT, tfinal, ep, nvecLen, iprob)
subroutine RHS (uvec, res, dt, ep, ttI, iprob)
subroutine JACOB (uvec, xinv, dt, ep, akk, ttI, iprob, nvecLen)
subroutine rungeadd (aE, aI, bE, bI, cE, cI, ns, bEH, bIH, icase, bD, svpB, alpha, al3N, al3D, al4N, al4D, ipred)
subroutine fit (x, y, ndata, sig, mwt, a, b, siga, sigb, chi2, q)
subroutine gser (gamser, a, x, gln)
subroutine gcf (gammcf, a, x, gln)
REAL gammq (a, x)
REAL gammln (xx)
Function Documentation
subroutine fit (REAL,dimension(ndata) x, REAL,dimension(ndata) y, INTEGER ndata, REAL,dimension(ndata) sig, INTEGER mwt, REAL a, REAL b, REAL siga, REAL sigb, REAL chi2, REAL q)
Definition at line 2999 of file general.RK6.f.
References gammq().
Referenced by test().
REAL gammln (REAL xx)
Definition at line 3131 of file general.RK6.f.
REAL gammq (REAL a, REAL x)
Definition at line 3117 of file general.RK6.f.
References gcf(), and gser().
Referenced by fit().
subroutine gcf (REAL gammcf, REAL a, REAL x, REAL gln)
Definition at line 3088 of file general.RK6.f.
Referenced by gammq().
subroutine gser (REAL gamser, REAL a, REAL x, REAL gln)
Definition at line 3059 of file general.RK6.f.
Referenced by gammq().
subroutine INIT (uvec , uexact , dt , iDT , tfinal , ep , nvecLen , iprob)
Definition at line 447 of file general.RK6.f.
Referenced by test().
subroutine JACOB (uvec , xinv , dt , ep , akk , ttI , iprob , nvecLen)
Definition at line 588 of file general.RK6.f.
Referenced by test().
subroutine RHS (uvec , res , dt , ep , ttI , iprob)
Definition at line 566 of file general.RK6.f.
Referenced by test().
subroutine rungeadd (aE , aI , bE , bI , cE , cI , ns , bEH , bIH , icase , bD , svpB , alpha , al3N , al3D , al4N , al4D , ipred)
Definition at line 742 of file general.RK6.f.
Referenced by test().
program test ()
Definition at line 1 of file general.RK6.f.
References fit(), INIT(), JACOB(), RHS(), and rungeadd().