Doxygen Fortran Example: vanderpol.RK.f File Reference
vanderpol.RK.f File Reference
Functions/Subroutines
program test
subroutine rungeadd (aE, aI, bE, bI, cE, cI, ns, bEH, bIH, icase)
subroutine fit (x, y, ndata, sig, mwt, a, b, siga, sigb, chi2, q)
subroutine gser (gamser, a, x, gln)
subroutine gcf (gammcf, a, x, gln)
REAL gammq (a, x)
REAL gammln (xx)
Function Documentation
subroutine fit (REAL,dimension(ndata) x, REAL,dimension(ndata) y, INTEGER ndata, REAL,dimension(ndata) sig, INTEGER mwt, REAL a, REAL b, REAL siga, REAL sigb, REAL chi2, REAL q)
Definition at line 3665 of file vanderpol.RK.f.
REAL gammln (REAL xx)
Definition at line 3797 of file vanderpol.RK.f.
REAL gammq (REAL a, REAL x)
Definition at line 3783 of file vanderpol.RK.f.
References gcf(), and gser().
subroutine gcf (REAL gammcf, REAL a, REAL x, REAL gln)
Definition at line 3754 of file vanderpol.RK.f.
subroutine gser (REAL gamser, REAL a, REAL x, REAL gln)
Definition at line 3725 of file vanderpol.RK.f.
subroutine rungeadd (aE , aI , bE , bI , cE , cI , ns , bEH , bIH , icase)
Definition at line 242 of file vanderpol.RK.f.
program test ()
Definition at line 1 of file vanderpol.RK.f.
References fit(), and rungeadd().