Doxygen Fortran Example: SBP_Coef_Module Module Reference
SBP_Coef_Module Module Reference
Functions/Subroutines
subroutine Define_CSR_Operators (n, h)
subroutine D1_periodic (n, nnz, ia, ja, a, h)
subroutine D2_periodic (n, nnz, ia, ja, a, h)
subroutine D1_242 (n, nnz, ia, ja, a, h)
subroutine D2_242 (n, nnz, ia, ja, a, h)
subroutine CSR_Filler (n, nnz, dmat, D1blk, D2blk, ia, ja, a)
subroutine test_error (order, n, ia, ja, a)
subroutine amux_local (n, x, y, a, ja, ia)
Variables
real(wp), parameter tol = 1.0e-12_wp
real(wp), dimension(:), allocatable Pmat
real(wp), dimension(:), allocatable Pinv
real(wp), dimension(:), allocatable D1
real(wp), dimension(:), allocatable D2
real(wp), dimension(:), allocatable D1_per
real(wp), dimension(:), allocatable D2_per
integer, dimension(:), allocatable iD1
integer, dimension(:), allocatable iD2
integer, dimension(:), allocatable jD1
integer, dimension(:), allocatable jD2
integer, dimension(:), allocatable iD1_per
integer, dimension(:), allocatable jD1_per
integer, dimension(:), allocatable iD2_per
integer, dimension(:), allocatable jD2_per
integer nnz_D2
integer nnz_D1_per
integer nnz_D1
integer nnz_D2_per
Function/Subroutine Documentation
subroutine SBP_Coef_Module::amux_local (integer,intent(in) n, real(wp),dimension(:),intent(in) x, real(wp),dimension(:),intent(out) y, real(wp),dimension(:),intent(in) a, integer,dimension(:),intent(in) ja, integer,dimension(:),intent(in) ia) [private]
Definition at line 464 of file SBP_Coef_Module.f90.
Referenced by test_error().
subroutine SBP_Coef_Module::CSR_Filler (integer,intent(in) n, integer,intent(in) nnz, real(wp),dimension(:),intent(in) dmat, real(wp),dimension(:,:),intent(in) D1blk, real(wp),dimension(:,:),intent(in) D2blk, integer,dimension(:),intent(out) ia, integer,dimension(:),intent(out) ja, real(wp),dimension(:),intent(out) a) [private]
Definition at line 321 of file SBP_Coef_Module.f90.
Referenced by D1_242(), and D2_242().
subroutine SBP_Coef_Module::D1_242 (integer,intent(in) n, integer,intent(in) nnz, integer,dimension(n+1),intent(out) ia, integer,dimension(nnz),intent(out) ja, real(wp),dimension(nnz),intent(out) a, real(wp),intent(in) h) [private]
Definition at line 170 of file SBP_Coef_Module.f90.
References CSR_Filler(), Pinv, Pmat, and test_error().
Referenced by Define_CSR_Operators().
subroutine SBP_Coef_Module::D1_periodic (integer,intent(in) n, integer,intent(in) nnz, integer,dimension(n+1),intent(out) ia, integer,dimension(nnz),intent(out) ja, real(wp),dimension(nnz),intent(out) a, real(wp),intent(in) h) [private]
Definition at line 59 of file SBP_Coef_Module.f90.
References Pinv, and Pmat.
Referenced by Define_CSR_Operators().
subroutine SBP_Coef_Module::D2_242 (integer,intent(in) n, integer,intent(in) nnz, integer,dimension(n+1),intent(out) ia, integer,dimension(nnz),intent(out) ja, real(wp),dimension(nnz),intent(out) a, real(wp),intent(in) h) [private]
Definition at line 241 of file SBP_Coef_Module.f90.
References CSR_Filler(), and test_error().
Referenced by Define_CSR_Operators().
subroutine SBP_Coef_Module::D2_periodic (integer,intent(in) n, integer,intent(in) nnz, integer,dimension(n+1),intent(out) ia, integer,dimension(nnz),intent(out) ja, real(wp),dimension(nnz),intent(out) a, real(wp),intent(in) h) [private]
Definition at line 118 of file SBP_Coef_Module.f90.
Referenced by Define_CSR_Operators().
subroutine SBP_Coef_Module::Define_CSR_Operators (integer,intent(in) n, real(wp),intent(in) h)
Definition at line 29 of file SBP_Coef_Module.f90.
References D1, D1_242(), D1_per, D1_periodic(), D2, D2_242(), D2_per, D2_periodic(), iD1, iD1_per, iD2, iD2_per, jD1, jD1_per, jD2, jD2_per, nnz_D1, nnz_D1_per, nnz_D2, nnz_D2_per, Pinv, and Pmat.
Referenced by Boscarino31_Mod::Boscarino31(), Broadwell_Mod::Broadwell(), Brusselator_mod::Brusselator(), and Burgers_Module::Burgers().
subroutine SBP_Coef_Module::test_error (integer,intent(in) order, integer,intent(in) n, integer,dimension(:),intent(in) ia, integer,dimension(:),intent(in) ja, real(wp),dimension(:),intent(in) a) [private]
Definition at line 397 of file SBP_Coef_Module.f90.
References amux_local().
Referenced by D1_242(), and D2_242().
Variable Documentation
real(wp),dimension(:),allocatable SBP_Coef_Module::D1
Definition at line 20 of file SBP_Coef_Module.f90.
Referenced by Burgers_Module::Build_Jac(), Burgers_Module::Burgers(), Burgers_Module::Burgers_dUdt(), control_variables::deallocate_vars(), and Define_CSR_Operators().
real(wp),dimension(:),allocatable SBP_Coef_Module::D1_per
Definition at line 20 of file SBP_Coef_Module.f90.
Referenced by Boscarino31_Mod::Bosc_dUdt(), Boscarino31_Mod::Boscarino31(), Broadwell_Mod::Broadwell(), Broadwell_Mod::Broadwell_dUdt(), control_variables::deallocate_vars(), and Define_CSR_Operators().
real(wp),dimension(:),allocatable SBP_Coef_Module::D2
Definition at line 20 of file SBP_Coef_Module.f90.
Referenced by Burgers_Module::Build_Jac(), Burgers_Module::Burgers_dUdt(), control_variables::deallocate_vars(), and Define_CSR_Operators().
real(wp),dimension(:),allocatable SBP_Coef_Module::D2_per
Definition at line 20 of file SBP_Coef_Module.f90.
Referenced by Brusselator_mod::Bruss_dUdt(), Brusselator_mod::Brusselator(), and Define_CSR_Operators().
integer,dimension(:),allocatable SBP_Coef_Module::iD1
Definition at line 21 of file SBP_Coef_Module.f90.
Referenced by Burgers_Module::Build_Jac(), Burgers_Module::Burgers_dUdt(), control_variables::deallocate_vars(), and Define_CSR_Operators().
integer,dimension(:),allocatable SBP_Coef_Module::iD1_per
Definition at line 21 of file SBP_Coef_Module.f90.
Referenced by Boscarino31_Mod::Bosc_dUdt(), Broadwell_Mod::Broadwell_dUdt(), and Define_CSR_Operators().
integer,dimension(:),allocatable SBP_Coef_Module::iD2
Definition at line 21 of file SBP_Coef_Module.f90.
Referenced by Burgers_Module::Build_Jac(), Burgers_Module::Burgers_dUdt(), control_variables::deallocate_vars(), and Define_CSR_Operators().
integer,dimension(:),allocatable SBP_Coef_Module::iD2_per
Definition at line 22 of file SBP_Coef_Module.f90.
Referenced by Brusselator_mod::Bruss_dUdt(), and Define_CSR_Operators().
integer,dimension(:),allocatable SBP_Coef_Module::jD1
Definition at line 21 of file SBP_Coef_Module.f90.
Referenced by Burgers_Module::Build_Jac(), Burgers_Module::Burgers_dUdt(), control_variables::deallocate_vars(), and Define_CSR_Operators().
integer,dimension(:),allocatable SBP_Coef_Module::jD1_per
Definition at line 21 of file SBP_Coef_Module.f90.
Referenced by Boscarino31_Mod::Bosc_dUdt(), Broadwell_Mod::Broadwell_dUdt(), and Define_CSR_Operators().
integer,dimension(:),allocatable SBP_Coef_Module::jD2
Definition at line 21 of file SBP_Coef_Module.f90.
Referenced by Burgers_Module::Build_Jac(), Burgers_Module::Burgers_dUdt(), control_variables::deallocate_vars(), and Define_CSR_Operators().
integer,dimension(:),allocatable SBP_Coef_Module::jD2_per
Definition at line 22 of file SBP_Coef_Module.f90.
Referenced by Brusselator_mod::Bruss_dUdt(), and Define_CSR_Operators().
integer SBP_Coef_Module::nnz_D1
Definition at line 23 of file SBP_Coef_Module.f90.
Referenced by Define_CSR_Operators().
integer SBP_Coef_Module::nnz_D1_per
Definition at line 23 of file SBP_Coef_Module.f90.
Referenced by Define_CSR_Operators().
integer SBP_Coef_Module::nnz_D2
Definition at line 23 of file SBP_Coef_Module.f90.
Referenced by Burgers_Module::Build_Jac(), Burgers_Module::Burgers(), and Define_CSR_Operators().
integer SBP_Coef_Module::nnz_D2_per
Definition at line 24 of file SBP_Coef_Module.f90.
Referenced by Brusselator_mod::Bruss_dUdt(), Brusselator_mod::Brusselator(), and Define_CSR_Operators().
real(wp),dimension(:),allocatable SBP_Coef_Module::Pinv
Definition at line 20 of file SBP_Coef_Module.f90.
Referenced by Burgers_Module::Build_Jac(), Burgers_Module::Burgers_dUdt(), D1_242(), D1_periodic(), control_variables::deallocate_vars(), and Define_CSR_Operators().
real(wp),dimension(:),allocatable SBP_Coef_Module::Pmat
Definition at line 20 of file SBP_Coef_Module.f90.
Referenced by D1_242(), D1_periodic(), control_variables::deallocate_vars(), and Define_CSR_Operators().
real(wp),parameter SBP_Coef_Module::tol = 1.0e-12_wp
Definition at line 13 of file SBP_Coef_Module.f90.