Doxygen Fortran Example: Boscarino31_Mod Module Reference
Boscarino31_Mod Module Reference
Functions/Subroutines
subroutine Boscarino31 (nveclen, ep, dt, tfinal, iDT, resE_vec, resI_vec, akk)
subroutine grid ()
subroutine exact_Bosc (u, eps)
subroutine Bosc_dUdt (u, dudt_D1, dudt_source, eps)
subroutine Bosc_Jac (dt, akk, a, ja, ia)
Variables
integer, parameter vecl = 256
real(wp), parameter a = 0.5_wp
real(wp), parameter xL = -1.0_wp
real(wp), parameter xR = 1.0_wp
real(wp), dimension(vecl/2) x
real(wp) dx
integer, dimension(4 *vecl jDeriv_comb_p)
real(wp), dimension(4 *vecl Deriv_comb_p)
real(wp), dimension(5 *vecl wrk_Jac)
integer, dimension(vecl+1) iSource_p
integer, dimension(vecl+1) iDeriv_comb_p
integer, dimension(vecl+1) iwrk_Jac
integer, dimension(5 *vecl jwrk_Jac)
real(wp), dimension(vecl) Source_p
integer, dimension(vecl) jSource_p
logical update_RHS
logical update_Jac
Function/Subroutine Documentation
subroutine Boscarino31_Mod::Bosc_dUdt (real(wp),dimension(vecl),intent(in) u, real(wp),dimension(vecl),intent(out) dudt_D1, real(wp),dimension(vecl),intent(out) dudt_source, real(wp),intent(in) eps) [private]
Definition at line 195 of file Boscarino31_mod.f90.
References a, matvec_module::amux(), unary_mod::aplb(), unary_mod::csort(), SBP_Coef_Module::D1_per, Deriv_comb_p, unary_mod::dperm(), SBP_Coef_Module::iD1_per, iDeriv_comb_p, iSource_p, SBP_Coef_Module::jD1_per, jDeriv_comb_p, jSource_p, Source_p, update_RHS, and vecl.
Referenced by Boscarino31().
subroutine Boscarino31_Mod::Bosc_Jac (real(wp),intent(in) dt, real(wp),intent(in) akk, real(wp),dimension(:),intent(in) a, integer,dimension(:),intent(in) ja, integer,dimension(:),intent(in) ia)
Definition at line 310 of file Boscarino31_mod.f90.
References Jacobian_CSR_Mod::aJac, unary_mod::aplsca(), Jacobian_CSR_Mod::iaJac, and Jacobian_CSR_Mod::jaJac.
Referenced by Boscarino31().
subroutine Boscarino31_Mod::Boscarino31 (integer,intent(out) nveclen, real(wp),intent(in) ep, real(wp),intent(inout) dt, real(wp),intent(out) tfinal, integer,intent(in) iDT, real(wp),dimension(vecl),intent(out) resE_vec, real(wp),dimension(vecl),intent(out) resI_vec, real(wp),intent(in) akk)
Definition at line 51 of file Boscarino31_mod.f90.
References a, Jacobian_CSR_Mod::Allocate_Jac_CSR_Storage(), unary_mod::aplb(), Bosc_dUdt(), Bosc_Jac(), SBP_Coef_Module::D1_per, SBP_Coef_Module::Define_CSR_Operators(), Deriv_comb_p, dx, exact_Bosc(), grid(), iDeriv_comb_p, iSource_p, iwrk_Jac, control_variables::Jac_case, jDeriv_comb_p, jSource_p, jwrk_Jac, precision_vars::pi, control_variables::probname, Source_p, precision_vars::two, update_Jac, update_RHS, vecl, wrk_Jac, and x.
Referenced by problemsub_mod::problemsub().
subroutine Boscarino31_Mod::exact_Bosc (real(wp),dimension(vecl),intent(out) u, real(wp),intent(in) eps) [private]
Definition at line 165 of file Boscarino31_mod.f90.
References vecl.
Referenced by Boscarino31().
subroutine Boscarino31_Mod::grid ()
Definition at line 153 of file Boscarino31_mod.f90.
References dx, vecl, x, xL, and xR.
Referenced by Boscarino31().
Variable Documentation
real(wp),parameter Boscarino31_Mod::a = 0.5_wp
Definition at line 24 of file Boscarino31_mod.f90.
Referenced by Bosc_dUdt(), and Boscarino31().
real(wp),dimension(4*vecl Boscarino31_Mod::Deriv_comb_p)
Definition at line 31 of file Boscarino31_mod.f90.
Referenced by Bosc_dUdt(), and Boscarino31().
real(wp) Boscarino31_Mod::dx
Definition at line 28 of file Boscarino31_mod.f90.
Referenced by Boscarino31(), and grid().
integer,dimension(vecl+1) Boscarino31_Mod::iDeriv_comb_p
Definition at line 33 of file Boscarino31_mod.f90.
Referenced by Bosc_dUdt(), and Boscarino31().
integer,dimension(vecl+1) Boscarino31_Mod::iSource_p
Definition at line 33 of file Boscarino31_mod.f90.
Referenced by Bosc_dUdt(), and Boscarino31().
integer,dimension(vecl+1) Boscarino31_Mod::iwrk_Jac
Definition at line 33 of file Boscarino31_mod.f90.
Referenced by Boscarino31().
integer,dimension(4*vecl Boscarino31_Mod::jDeriv_comb_p)
Definition at line 30 of file Boscarino31_mod.f90.
Referenced by Bosc_dUdt(), and Boscarino31().
integer,dimension(vecl) Boscarino31_Mod::jSource_p
Definition at line 37 of file Boscarino31_mod.f90.
Referenced by Bosc_dUdt(), and Boscarino31().
integer,dimension(5*vecl Boscarino31_Mod::jwrk_Jac)
Definition at line 34 of file Boscarino31_mod.f90.
Referenced by Boscarino31().
real(wp),dimension(vecl) Boscarino31_Mod::Source_p
Definition at line 36 of file Boscarino31_mod.f90.
Referenced by Bosc_dUdt(), and Boscarino31().
logical Boscarino31_Mod::update_Jac
Definition at line 38 of file Boscarino31_mod.f90.
Referenced by Boscarino31().
logical Boscarino31_Mod::update_RHS
Definition at line 38 of file Boscarino31_mod.f90.
Referenced by Bosc_dUdt(), and Boscarino31().
integer,parameter Boscarino31_Mod::vecl = 256
Definition at line 23 of file Boscarino31_mod.f90.
Referenced by Bosc_dUdt(), Boscarino31(), exact_Bosc(), and grid().
real(wp),dimension(5*vecl Boscarino31_Mod::wrk_Jac)
Definition at line 32 of file Boscarino31_mod.f90.
Referenced by Boscarino31().
real(wp),dimension(vecl/2) Boscarino31_Mod::x
Definition at line 27 of file Boscarino31_mod.f90.
Referenced by Boscarino31(), and grid().
real(wp),parameter Boscarino31_Mod::xL = -1.0_wp
Definition at line 25 of file Boscarino31_mod.f90.
Referenced by grid().
real(wp),parameter Boscarino31_Mod::xR = 1.0_wp
Definition at line 25 of file Boscarino31_mod.f90.
Referenced by grid().