Doxygen Fortran Example: matvec_module Module Reference
matvec_module Module Reference
Functions/Subroutines
subroutine amux (n, x, y, a, ja, ia)
subroutine amux_M_rhs (n, m, nnz, x, y, a, ja, ia)
subroutine atmux (n, x, y, a, ja, ia)
subroutine atmuxr (m, n, x, y, a, ja, ia)
subroutine lsol (n, x, y, al, jal, ial)
subroutine lsol_M_rhs (n, m, x, y, al, jal, ial)
subroutine ldsol (n, x, y, al, jal)
subroutine usol (n, x, y, au, jau, iau)
subroutine usol_M_rhs (n, m, x, y, au, jau, iau)
subroutine udsol (n, x, y, au, jau)
Function/Subroutine Documentation
subroutine matvec_module::amux (integer n, real(wp),dimension(*) x, real(wp),dimension(*) y, real(wp),dimension(*) a, integer,dimension(*) ja, integer,dimension(*) ia)
Definition at line 39 of file matvec_module.f90.
Referenced by Boscarino31_Mod::Bosc_dUdt(), Broadwell_Mod::Broadwell_dUdt(), Brusselator_mod::Bruss_dUdt(), Burgers_Module::Build_Jac(), and Burgers_Module::Burgers_dUdt().
subroutine matvec_module::amux_M_rhs (integer,intent(in) n, integer,intent(in) m, integer,intent(in) nnz, real(wp),dimension(:,:),intent(in) x, real(wp),dimension(:,:),intent(out) y, real(wp),dimension(:),intent(in) a, integer,dimension(:),intent(in) ja, integer,dimension(:),intent(in) ia)
Definition at line 85 of file matvec_module.f90.
subroutine matvec_module::atmux (integer n, real(wp),dimension(*) x, real(wp),dimension(*) y, real(wp),dimension(*) a, integer,dimension(*) ja, integer,dimension(*) ia)
Definition at line 147 of file matvec_module.f90.
subroutine matvec_module::atmuxr (integer m, integer n, real(wp),dimension(*) x, real(wp),dimension(*) y, real(wp),dimension(*) a, integer,dimension(*) ja, integer,dimension(*) ia)
Definition at line 195 of file matvec_module.f90.
subroutine matvec_module::ldsol (integer n, real(wp),dimension(n) x, real(wp),dimension(n) y, real(wp),dimension(*) al, integer,dimension(*) jal) [private]
Definition at line 345 of file matvec_module.f90.
subroutine matvec_module::lsol (integer n, real(wp),dimension(n) x, real(wp),dimension(n) y, real(wp),dimension(*) al, integer,dimension(*) jal, integer,dimension(n+1) ial)
Definition at line 246 of file matvec_module.f90.
subroutine matvec_module::lsol_M_rhs (integer,intent(in) n, integer,intent(in) m, real(wp),dimension(m,n),intent(out) x, real(wp),dimension(m,n),intent(in) y, real(wp),dimension(*),intent(in) al, integer,dimension(*),intent(in) jal, integer,dimension(n+1),intent(in) ial)
Definition at line 290 of file matvec_module.f90.
subroutine matvec_module::udsol (integer n, real(wp),dimension(n) x, real(wp),dimension(n) y, real(wp),dimension(*) au, integer,dimension(*) jau) [private]
Definition at line 484 of file matvec_module.f90.
subroutine matvec_module::usol (integer n, real(wp),dimension(n) x, real(wp),dimension(n) y, real(wp),dimension(*) au, integer,dimension(*) jau, integer,dimension(n+1) iau)
Definition at line 389 of file matvec_module.f90.
subroutine matvec_module::usol_M_rhs (integer,intent(in) n, integer,intent(in) m, real(wp),dimension(m,n),intent(out) x, real(wp),dimension(m,n),intent(in) y, real(wp),dimension(*),intent(in) au, integer,dimension(*),intent(in) jau, integer,dimension(n+1),intent(in) iau)
Definition at line 431 of file matvec_module.f90.