Doxygen Fortran Example: Burgers_Module Module Reference
Burgers_Module Module Reference
Functions/Subroutines
subroutine Burgers (nveclen, eq, ep, dt, tfinal, iDT, time, resE_vec, resI_vec, akk)
subroutine grid ()
subroutine exact_Burg (u, eps, time)
subroutine Burgers_dUdt (u, dudt, time, eps, dt)
subroutine Build_Jac (u, eps, dt, akk, time)
real(wp) NL_Burg_exactsolution (xin, tin, eps)
real(wp) NL_Burg_exact_derivative (xin, tin, eps)
Variables
real(wp) dx
character(120), parameter exact_solution
real(wp), parameter sig0 = -1.0_wp
real(wp), parameter sig1 = +1.0_wp
integer, parameter vecl = 128
integer, parameter neq = 1
real(wp), dimension(vecl) x
real(wp), parameter xL = 0.0_wp
real(wp), parameter xR = 1.0_wp
real(wp), dimension(4), parameter d1vec0 = (/-24.0_wp/17.0_wp, +59.0_wp/34.0_wp, -4.0_wp/17.0_wp, -3.0_wp/34.0_wp/)
real(wp), dimension(4), parameter d1vec1 = (/+ 3.0_wp/34.0_wp, + 4.0_wp/17.0_wp, -59.0_wp/34.0_wp, +24.0_wp/17.0_wp/)
Function/Subroutine Documentation
subroutine Burgers_Module::Build_Jac (real(wp),dimension(vecl),intent(in) u, real(wp),intent(in) eps, real(wp),intent(in) dt, real(wp),intent(in) akk, real(wp),intent(in) time)
Definition at line 227 of file Burgers_Mod.f90.
References Jacobian_CSR_Mod::aJac, unary_mod::amudia(), matvec_module::amux(), unary_mod::aplb(), unary_mod::apldia(), unary_mod::aplsca(), SBP_Coef_Module::D1, d1vec0, d1vec1, SBP_Coef_Module::D2, unary_mod::diamua(), dx, Jacobian_CSR_Mod::iaJac, SBP_Coef_Module::iD1, SBP_Coef_Module::iD2, Jacobian_CSR_Mod::jaJac, SBP_Coef_Module::jD1, SBP_Coef_Module::jD2, NL_Burg_exactsolution(), SBP_Coef_Module::nnz_D2, SBP_Coef_Module::Pinv, sig0, sig1, precision_vars::third, precision_vars::twothird, vecl, and x.
Referenced by Burgers().
subroutine Burgers_Module::Burgers (integer,intent(out) nveclen, integer,intent(out) eq, real(wp),intent(in) ep, real(wp),intent(inout) dt, real(wp),intent(out) tfinal, integer,intent(in) iDT, real(wp),intent(in) time, real(wp),dimension(vecl),intent(out) resE_vec, real(wp),dimension(vecl),intent(out) resI_vec, real(wp),intent(in) akk)
Definition at line 56 of file Burgers_Mod.f90.
References Jacobian_CSR_Mod::Allocate_Jac_CSR_Storage(), Build_Jac(), Burgers_dUdt(), SBP_Coef_Module::D1, SBP_Coef_Module::Define_CSR_Operators(), dx, exact_Burg(), grid(), neq, SBP_Coef_Module::nnz_D2, control_variables::probname, and vecl.
Referenced by problemsub_mod::problemsub().
subroutine Burgers_Module::Burgers_dUdt (real(wp),dimension(vecl),intent(in) u, real(wp),dimension(vecl),intent(out) dudt, real(wp),intent(in) time, real(wp),intent(in) eps, real(wp),intent(in) dt) [private]
Definition at line 166 of file Burgers_Mod.f90.
References matvec_module::amux(), SBP_Coef_Module::D1, d1vec0, d1vec1, SBP_Coef_Module::D2, dx, precision_vars::half, SBP_Coef_Module::iD1, SBP_Coef_Module::iD2, SBP_Coef_Module::jD1, SBP_Coef_Module::jD2, NL_Burg_exact_derivative(), NL_Burg_exactsolution(), SBP_Coef_Module::Pinv, sig0, sig1, precision_vars::third, precision_vars::twothird, vecl, and x.
Referenced by Burgers().
subroutine Burgers_Module::exact_Burg (real(wp),dimension(vecl),intent(out) u, real(wp),intent(in) eps, real(wp),intent(in) time) [private]
Definition at line 153 of file Burgers_Mod.f90.
References NL_Burg_exactsolution(), vecl, and x.
Referenced by Burgers().
subroutine Burgers_Module::grid ()
Definition at line 141 of file Burgers_Mod.f90.
References dx, vecl, x, xL, and xR.
Referenced by Burgers().
real(wp) Burgers_Module::NL_Burg_exact_derivative (real(wp),intent(in) xin, real(wp),intent(in) tin, real(wp),intent(in) eps) [private]
Definition at line 390 of file Burgers_Mod.f90.
References exact_solution.
Referenced by Burgers_dUdt().
real(wp) Burgers_Module::NL_Burg_exactsolution (real(wp),intent(in) xin, real(wp),intent(in) tin, real(wp),intent(in) eps)
Definition at line 363 of file Burgers_Mod.f90.
References exact_solution.
Referenced by Build_Jac(), Burgers_dUdt(), and exact_Burg().
Variable Documentation
real(wp),dimension(4),parameter Burgers_Module::d1vec0 = (/-24.0_wp/17.0_wp, +59.0_wp/34.0_wp, -4.0_wp/17.0_wp, -3.0_wp/34.0_wp/)
Definition at line 33 of file Burgers_Mod.f90.
Referenced by Build_Jac(), and Burgers_dUdt().
real(wp),dimension(4),parameter Burgers_Module::d1vec1 = (/+ 3.0_wp/34.0_wp, + 4.0_wp/17.0_wp, -59.0_wp/34.0_wp, +24.0_wp/17.0_wp/)
Definition at line 38 of file Burgers_Mod.f90.
Referenced by Build_Jac(), and Burgers_dUdt().
real(wp) Burgers_Module::dx
Definition at line 22 of file Burgers_Mod.f90.
Referenced by Build_Jac(), Burgers(), Burgers_dUdt(), and grid().
character(120),parameter Burgers_Module::exact_solution
Definition at line 23 of file Burgers_Mod.f90.
Referenced by NL_Burg_exact_derivative(), and NL_Burg_exactsolution().
integer,parameter Burgers_Module::neq = 1
Definition at line 29 of file Burgers_Mod.f90.
Referenced by Burgers().
real(wp),parameter Burgers_Module::sig0 = -1.0_wp
Definition at line 25 of file Burgers_Mod.f90.
Referenced by Build_Jac(), and Burgers_dUdt().
real(wp),parameter Burgers_Module::sig1 = +1.0_wp
Definition at line 26 of file Burgers_Mod.f90.
Referenced by Build_Jac(), and Burgers_dUdt().
integer,parameter Burgers_Module::vecl = 128
Definition at line 28 of file Burgers_Mod.f90.
Referenced by Build_Jac(), Burgers(), Burgers_dUdt(), exact_Burg(), and grid().
real(wp),dimension(vecl) Burgers_Module::x
Definition at line 30 of file Burgers_Mod.f90.
Referenced by Build_Jac(), Burgers_dUdt(), exact_Burg(), and grid().
real(wp),parameter Burgers_Module::xL = 0.0_wp
Definition at line 31 of file Burgers_Mod.f90.
Referenced by grid().
real(wp),parameter Burgers_Module::xR = 1.0_wp
Definition at line 31 of file Burgers_Mod.f90.
Referenced by grid().