Doxygen Fortran Example: blas_module Module Reference
blas_module Module Reference
Functions/Subroutines
subroutine dcopy (n, dx, incx, dy, incy)
real(wp) ddot (n, dx, incx, dy, incy)
real(wp) dasum (n, dx, incx)
subroutine daxpy (n, da, dx, incx, dy, incy)
real(wp) dnrm2 (n, dx, incx)
subroutine dscal (n, da, dx, incx)
subroutine dswap (n, dx, incx, dy, incy)
integer idamax (n, dx, incx)
subroutine drot (n, dx, incx, dy, incy, c, s)
subroutine drotg (da, db, c, s)
subroutine ccopy (n, cx, incx, cy, incy)
subroutine cscal (n, ca, cx, incx)
subroutine csrot (n, cx, incx, cy, incy, c, s)
subroutine cswap (n, cx, incx, cy, incy)
subroutine csscal (n, sa, cx, incx)
integer lctcsr (i, j, ja, ia)
Function/Subroutine Documentation
subroutine blas_module::ccopy (integer n, complex,dimension(*) cx, integer incx, complex,dimension(*) cy, integer incy) [private]
Definition at line 554 of file blas_module.f90.
subroutine blas_module::cscal (integer n, complex ca, complex,dimension(*) cx, integer incx) [private]
Definition at line 589 of file blas_module.f90.
subroutine blas_module::csrot (integer n, complex,dimension(*) cx, integer incx, complex,dimension(*) cy, integer incy, real c, real s) [private]
Definition at line 618 of file blas_module.f90.
subroutine blas_module::csscal (integer n, real sa, complex,dimension(*) cx, integer incx) [private]
Definition at line 697 of file blas_module.f90.
subroutine blas_module::cswap (integer n, complex,dimension(*) cx, integer incx, complex,dimension(*) cy, integer incy) [private]
Definition at line 659 of file blas_module.f90.
real(wp) blas_module::dasum (integer n, real(wp),dimension(*) dx, integer incx) [private]
Definition at line 120 of file blas_module.f90.
subroutine blas_module::daxpy (integer,intent(in) n, real(wp),intent(in) da, real(wp),dimension(*),intent(in) dx, integer,intent(in) incx, real(wp),dimension(*),intent(out) dy, integer,intent(in) incy)
Definition at line 164 of file blas_module.f90.
Referenced by ilut_module::pgmres().
subroutine blas_module::dcopy (integer n, real(wp),dimension(*) dx, integer incx, real(wp),dimension(*) dy, integer incy)
Definition at line 17 of file blas_module.f90.
real(wp) blas_module::ddot (integer n, real(wp),dimension(*) dx, integer incx, real(wp),dimension(*) dy, integer incy)
Definition at line 69 of file blas_module.f90.
Referenced by ilut_module::pgmres().
real(wp) blas_module::dnrm2 (n , real(wp),dimension(*) dx, incx)
Definition at line 220 of file blas_module.f90.
Referenced by ilut_module::pgmres().
subroutine blas_module::drot (integer n, real(wp),dimension(*) dx, integer incx, real(wp),dimension(*) dy, integer incy, real(wp) c, real(wp) s) [private]
Definition at line 486 of file blas_module.f90.
subroutine blas_module::drotg (real(wp) da, real(wp) db, real(wp) c, real(wp) s) [private]
Definition at line 525 of file blas_module.f90.
subroutine blas_module::dscal (integer n, real(wp) da, real(wp),dimension(*) dx, integer incx) [private]
Definition at line 345 of file blas_module.f90.
subroutine blas_module::dswap (integer n, real(wp),dimension(*) dx, integer incx, real(wp),dimension(*) dy, integer incy) [private]
Definition at line 388 of file blas_module.f90.
integer blas_module::idamax (integer n, real(wp),dimension(*) dx, integer incx) [private]
Definition at line 446 of file blas_module.f90.
integer blas_module::lctcsr (integer i, integer j, integer,dimension(*) ja, integer,dimension(*) ia)
Definition at line 727 of file blas_module.f90.