Doxygen Fortran Example: control_variables Module Reference
control_variables Module Reference
Functions/Subroutines
subroutine allocate_vars (nveclen, is)
subroutine deallocate_vars ()
Variables
character(len=80), parameter Temporal_Splitting
character(len=9) probname
character(len=6) Jac_case
character(len=80) programstep
integer, parameter isamp = 71
integer, parameter jmax = 81
integer, parameter jactual = 81
real(wp) tol
real(wp) dt_error_tol
real(wp), dimension(:), allocatable uvec
real(wp), dimension(:), allocatable uexact
real(wp), dimension(:), allocatable b
real(wp), dimension(:), allocatable usum
real(wp), dimension(:), allocatable uveco
real(wp), dimension(:), allocatable errvec
real(wp), dimension(:), allocatable errvecT
real(wp), dimension(:), allocatable tmpvec
real(wp), dimension(:,:),
allocatable resE
real(wp), dimension(:,:),
allocatable resI
real(wp), dimension(:,:),
allocatable error
real(wp), dimension(:,:),
allocatable errorP
real(wp), dimension(:,:),
allocatable xjac
real(wp), dimension(:,:),
allocatable b1save
real(wp), dimension(:,:),
allocatable b1Psave
real(wp), dimension(:,:),
allocatable ustage
real(wp), dimension(:,:),
allocatable predvec
real(wp), dimension(:,:),
allocatable errorL2
real(wp), dimension(:,:),
allocatable b1L2save
Function/Subroutine Documentation
subroutine control_variables::allocate_vars (integer,intent(in) nveclen, integer,intent(in) is)
Definition at line 49 of file control_variables.f90.
References b, b1L2save, b1Psave, b1save, error, errorL2, errorP, errvec, errvecT, isamp, jmax, predvec, resE, resI, tmpvec, uexact, ustage, usum, uvec, uveco, and xjac.
Referenced by test_cases().
subroutine control_variables::deallocate_vars ()
Definition at line 73 of file control_variables.f90.
References Jacobian_CSR_Mod::aJac, Jacobian_CSR_Mod::aLUJac, b, b1L2save, b1Psave, b1save, SBP_Coef_Module::D1, SBP_Coef_Module::D1_per, SBP_Coef_Module::D2, error, errorL2, errorP, errvec, errvecT, Jacobian_CSR_Mod::iaJac, SBP_Coef_Module::iD1, SBP_Coef_Module::iD2, Jacobian_CSR_Mod::iw, Jacobian_CSR_Mod::jaJac, SBP_Coef_Module::jD1, SBP_Coef_Module::jD2, Jacobian_CSR_Mod::jLUJac, Jacobian_CSR_Mod::jUJac, SBP_Coef_Module::Pinv, SBP_Coef_Module::Pmat, predvec, resE, resI, tmpvec, uexact, ustage, usum, uvec, uveco, and xjac.
Referenced by test_cases().
Variable Documentation
real(wp),dimension(:),allocatable control_variables::b
Definition at line 38 of file control_variables.f90.
Referenced by allocate_vars(), deallocate_vars(), and output_module::output_terminal_iteration().
real(wp),dimension(:,:),allocatable control_variables::b1L2save
Definition at line 42 of file control_variables.f90.
Referenced by allocate_vars(), and deallocate_vars().
real(wp),dimension(:,:),allocatable control_variables::b1Psave
Definition at line 41 of file control_variables.f90.
Referenced by allocate_vars(), and deallocate_vars().
real(wp),dimension(:,:),allocatable control_variables::b1save
Definition at line 41 of file control_variables.f90.
Referenced by allocate_vars(), and deallocate_vars().
real(wp) control_variables::dt_error_tol
Definition at line 36 of file control_variables.f90.
Referenced by output_module::output_terminal_iteration().
real(wp),dimension(:,:),allocatable control_variables::error
Definition at line 40 of file control_variables.f90.
Referenced by allocate_vars(), deallocate_vars(), and output_module::output_terminal_iteration().
real(wp),dimension(:,:),allocatable control_variables::errorL2
Definition at line 42 of file control_variables.f90.
Referenced by allocate_vars(), deallocate_vars(), and output_module::output_terminal_iteration().
real(wp),dimension(:,:),allocatable control_variables::errorP
Definition at line 40 of file control_variables.f90.
Referenced by allocate_vars(), deallocate_vars(), and output_module::output_terminal_iteration().
real(wp),dimension(:),allocatable control_variables::errvec
Definition at line 39 of file control_variables.f90.
Referenced by allocate_vars(), and deallocate_vars().
real(wp),dimension(:),allocatable control_variables::errvecT
Definition at line 39 of file control_variables.f90.
Referenced by allocate_vars(), deallocate_vars(), and output_module::output_conv_error().
integer,parameter control_variables::isamp = 71
Definition at line 32 of file control_variables.f90.
Referenced by allocate_vars(), and test_cases().
character(len=6) control_variables::Jac_case
Definition at line 30 of file control_variables.f90.
Referenced by Boscarino31_Mod::Boscarino31(), Broadwell_Mod::Broadwell(), and Brusselator_mod::Brusselator().
integer,parameter control_variables::jactual = 81
Definition at line 34 of file control_variables.f90.
Referenced by output_module::output_conv_stiff().
integer,parameter control_variables::jmax = 81
Definition at line 33 of file control_variables.f90.
Referenced by allocate_vars(), and test_cases().
real(wp),dimension(:,:),allocatable control_variables::predvec
Definition at line 41 of file control_variables.f90.
Referenced by allocate_vars(), deallocate_vars(), and Stage_value_module::Stage_Value_Predictor1().
character(len=9) control_variables::probname
Definition at line 29 of file control_variables.f90.
Referenced by Boscarino31_Mod::Boscarino31(), Broadwell_Mod::Broadwell(), Brusselator_mod::Brusselator(), Burgers_Module::Burgers(), output_module::init_output_files(), Kaps_mod::Kaps(), Kreiss_mod::Kreiss(), Lorenz_mod::Lorenz(), Oregonator_mod::Oregonator(), output_module::output_conv_stiff(), output_module::output_names(), Pureschi_mod::Pureschi(), Rossler_mod::Rossler_Chaos(), output_module::set_file_loc(), and vanderPol_mod::vanderPol().
character(len=80) control_variables::programstep
Definition at line 31 of file control_variables.f90.
real(wp),dimension(:,:),allocatable control_variables::resE
Definition at line 40 of file control_variables.f90.
Referenced by allocate_vars(), deallocate_vars(), and problemsub_mod::problemsub().
real(wp),dimension(:,:),allocatable control_variables::resI
Definition at line 40 of file control_variables.f90.
Referenced by allocate_vars(), Newton::Build_Rnewton(), deallocate_vars(), and problemsub_mod::problemsub().
character(len=80),parameter control_variables::Temporal_Splitting
Definition at line 26 of file control_variables.f90.
real(wp),dimension(:),allocatable control_variables::tmpvec
Definition at line 39 of file control_variables.f90.
Referenced by allocate_vars(), and deallocate_vars().
real(wp) control_variables::tol
Definition at line 36 of file control_variables.f90.
Referenced by Newton::check_exit().
real(wp),dimension(:),allocatable control_variables::uexact
Definition at line 38 of file control_variables.f90.
Referenced by allocate_vars(), deallocate_vars(), and output_module::output_conv_error().
real(wp),dimension(:,:),allocatable control_variables::ustage
Definition at line 41 of file control_variables.f90.
Referenced by allocate_vars(), deallocate_vars(), Stage_value_module::Stage_Value_Predictor1(), and Stage_value_module::Stage_Value_Predictor2().
real(wp),dimension(:),allocatable control_variables::usum
Definition at line 38 of file control_variables.f90.
Referenced by allocate_vars(), Newton::Build_Rnewton(), deallocate_vars(), and Newton::Newton_Iteration().
real(wp),dimension(:),allocatable control_variables::uvec
Definition at line 38 of file control_variables.f90.
Referenced by allocate_vars(), Newton::check_exit(), deallocate_vars(), Newton::LU_solver(), Newton::newt_line_search(), Newton::Newton_Iteration(), output_module::output_conv_error(), Newton::QR_decomp(), and Stage_value_module::Stage_Value_Predictor2().
real(wp),dimension(:),allocatable control_variables::uveco
Definition at line 38 of file control_variables.f90.
Referenced by allocate_vars(), deallocate_vars(), and Stage_value_module::Stage_Value_Predictor2().
real(wp),dimension(:,:),allocatable control_variables::xjac
Definition at line 40 of file control_variables.f90.
Referenced by allocate_vars(), deallocate_vars(), Kaps_mod::Kaps(), Kreiss_mod::Kreiss(), Lorenz_mod::Lorenz(), Newton::newt_line_search(), Newton::Newton_Iteration(), Oregonator_mod::Oregonator(), Pureschi_mod::Pureschi(), Rossler_mod::Rossler_Chaos(), and vanderPol_mod::vanderPol().