Doxygen Fortran Example: poly_fit_Mod Module Reference
poly_fit_Mod Module Reference
Functions/Subroutines
subroutine fit (x, y, ndata, sig, mwt, a, b, siga, sigb, chi2, q)
real(wp) gammln (xx)
real(wp) gammq (a, x)
subroutine gcf (gammcf, a, x, gln)
subroutine gser (gamser, a, x, gln)
Function/Subroutine Documentation
subroutine poly_fit_Mod::fit (real(wp),dimension(ndata),intent(in) x, real(wp),dimension(ndata),intent(in) y, integer,intent(in) ndata, real(wp),dimension(ndata),intent(in) sig, integer,intent(in) mwt, real(wp),intent(out) a, real(wp),intent(out) b, real(wp),intent(out) siga, real(wp),intent(out) sigb, real(wp),intent(out) chi2, real(wp),intent(out) q)
Definition at line 21 of file poly_fit_Mod.f90.
References gammq().
real(wp) poly_fit_Mod::gammln (real(wp),intent(in) xx) [private]
Definition at line 87 of file poly_fit_Mod.f90.
Referenced by gcf(), and gser().
real(wp) poly_fit_Mod::gammq (real(wp),intent(in) a, real(wp),intent(in) x) [private]
Definition at line 115 of file poly_fit_Mod.f90.
References gcf(), and gser().
Referenced by fit().
subroutine poly_fit_Mod::gcf (real(wp),intent(out) gammcf, real(wp),intent(in) a, real(wp),intent(in) x, real(wp),intent(out) gln) [private]
Definition at line 139 of file poly_fit_Mod.f90.
References gammln().
Referenced by gammq().
subroutine poly_fit_Mod::gser (real(wp),intent(out) gamser, real(wp),intent(in) a, real(wp),intent(in) x, real(wp),intent(out) gln) [private]
Definition at line 176 of file poly_fit_Mod.f90.
References gammln().
Referenced by gammq().