Doxygen Fortran Example: problemsub_mod Module Reference
problemsub_mod Module Reference
Functions/Subroutines
subroutine problemsub (iprob, nveclen, ep, dt, tfinal, iDT, time, akk, L)
Function/Subroutine Documentation
subroutine problemsub_mod::problemsub (integer,intent(in) iprob, integer,intent(out) nveclen, real(wp),intent(in) ep, real(wp),intent(inout) dt, real(wp),intent(out) tfinal, integer,intent(in) iDT, real(wp),intent(in) time, real(wp),intent(in) akk, integer,intent(in) L)
Definition at line 29 of file problemsub.f90.
References Boscarino31_Mod::Boscarino31(), Brusselator_mod::Brusselator(), Burgers_Module::Burgers(), Kaps_mod::Kaps(), Kreiss_mod::Kreiss(), Lorenz_mod::Lorenz(), Oregonator_mod::Oregonator(), Pureschi_mod::Pureschi(), control_variables::resE, control_variables::resI, Rossler_mod::Rossler_Chaos(), and vanderPol_mod::vanderPol().
Referenced by Newton::Build_Jac(), Newton::Build_Rnewton(), and test_cases().