Doxygen Fortran Example: runge_kutta Module Reference
runge_kutta Module Reference
Functions/Subroutines
subroutine rungeadd (icase)
Variables
integer, parameter is = 9
character(len=25) casename
real(wp), dimension(is, is) aE
real(wp), dimension(is, is) aI
real(wp), dimension(is) bE
real(wp), dimension(is) bI
real(wp), dimension(is) cE
real(wp), dimension(is) cI
integer ns
real(wp), dimension(is) bEH
real(wp), dimension(is) bIH
real(wp), dimension(is, 4) bD
real(wp), dimension(is, is, 0:is) svpB
real(wp), dimension(is, is) alpha
real(wp), dimension(is, is) al3N
real(wp), dimension(is, is) al3D
real(wp), dimension(is, is) al4N
real(wp), dimension(is, is) al4D
Function/Subroutine Documentation
subroutine runge_kutta::rungeadd (integer,intent(in) icase)
Definition at line 44 of file runge_kutta.f90.
References aE, aI, al3D, al3N, al4D, al4N, alpha, bD, casename, cE, cI, is, ns, and svpB.
Referenced by test_cases().
Variable Documentation
real(wp),dimension(is,is) runge_kutta::aE
Definition at line 22 of file runge_kutta.f90.
Referenced by rungeadd(), and test_cases().
real(wp),dimension(is,is) runge_kutta::aI
Definition at line 23 of file runge_kutta.f90.
Referenced by rungeadd(), and test_cases().
real(wp),dimension(is,is) runge_kutta::al3D
Definition at line 35 of file runge_kutta.f90.
Referenced by rungeadd().
real(wp),dimension(is,is) runge_kutta::al3N
Definition at line 34 of file runge_kutta.f90.
Referenced by rungeadd().
real(wp),dimension(is,is) runge_kutta::al4D
Definition at line 37 of file runge_kutta.f90.
Referenced by rungeadd().
real(wp),dimension(is,is) runge_kutta::al4N
Definition at line 36 of file runge_kutta.f90.
Referenced by rungeadd().
real(wp),dimension(is,is) runge_kutta::alpha
Definition at line 33 of file runge_kutta.f90.
Referenced by rungeadd(), and Stage_value_module::Stage_Value_Predictor2().
real(wp),dimension(is,4) runge_kutta::bD
Definition at line 31 of file runge_kutta.f90.
Referenced by rungeadd().
real(wp),dimension(is) runge_kutta::bE
Definition at line 24 of file runge_kutta.f90.
Referenced by test_cases().
real(wp),dimension(is) runge_kutta::bEH
Definition at line 29 of file runge_kutta.f90.
Referenced by test_cases().
real(wp),dimension(is) runge_kutta::bI
Definition at line 25 of file runge_kutta.f90.
Referenced by test_cases().
real(wp),dimension(is) runge_kutta::bIH
Definition at line 30 of file runge_kutta.f90.
Referenced by test_cases().
character(len=25) runge_kutta::casename
Definition at line 20 of file runge_kutta.f90.
Referenced by output_module::init_output_files(), output_module::output_conv_stiff(), output_module::output_names(), rungeadd(), and output_module::set_file_loc().
real(wp),dimension(is) runge_kutta::cE
Definition at line 26 of file runge_kutta.f90.
Referenced by rungeadd().
real(wp),dimension(is) runge_kutta::cI
Definition at line 27 of file runge_kutta.f90.
Referenced by rungeadd().
integer,parameter runge_kutta::is = 9
Definition at line 19 of file runge_kutta.f90.
Referenced by rungeadd(), and test_cases().
integer runge_kutta::ns
Definition at line 28 of file runge_kutta.f90.
Referenced by output_module::output_terminal_final(), rungeadd(), Stage_value_module::Stage_Value_Predictor1(), and test_cases().
real(wp),dimension(is,is,0:is) runge_kutta::svpB
Definition at line 32 of file runge_kutta.f90.
Referenced by rungeadd().