Doxygen Fortran Example: Brusselator_mod Module Reference
Brusselator_mod Module Reference
Functions/Subroutines
subroutine Brusselator (nveclen, eq, ep, dt, tfinal, iDT, resE_vec, resI_vec, akk)
subroutine grid ()
subroutine Bruss_dUdt (vec, dudt_deriv2, dudt_source, eps)
subroutine Build_Source_Jac (vec, Source_p, jSource_p, iSource_p)
subroutine Build_Jac (dt, akk, a, ja, ia)
Variables
integer, parameter vecl = 32
integer, parameter neq = 2
real(wp), parameter xL = 0.0_wp
real(wp), parameter xR = 1.0_wp
real(wp), dimension(vecl) x
real(wp) dx
integer, dimension(10 *vecl jDeriv2_p)
real(wp), dimension(10 *vecl Deriv2_p)
integer, dimension(vecl *2+1 iDeriv2_p)
real(wp), dimension(vecl *2 exact_Bruss)(eps)
Function/Subroutine Documentation
subroutine Brusselator_mod::Bruss_dUdt (real(wp),dimension(:),intent(in) vec, real(wp),dimension(vecl*2),intent(out) dudt_deriv2, real(wp),dimension(vecl*2),intent(out) dudt_source, real(wp),intent(in) eps) [private]
Definition at line 200 of file brusselator_2.f90.
References matvec_module::amux(), SBP_Coef_Module::D2_per, Deriv2_p, unary_mod::dperm(), SBP_Coef_Module::iD2_per, iDeriv2_p, SBP_Coef_Module::jD2_per, jDeriv2_p, SBP_Coef_Module::nnz_D2_per, and vecl.
subroutine Brusselator_mod::Brusselator (integer,intent(out) nveclen, integer,intent(out) eq, real(wp),intent(in) ep, real(wp),intent(inout) dt, real(wp),intent(out) tfinal, integer,intent(in) iDT, real(wp),dimension(vecl*2),intent(out) resE_vec, real(wp),dimension(vecl*2),intent(out) resI_vec, real(wp),intent(in) akk)
Definition at line 48 of file brusselator_2.f90.
References Jacobian_CSR_Mod::Allocate_Jac_CSR_Storage(), unary_mod::aplb(), Build_Jac(), Build_Source_Jac(), SBP_Coef_Module::D2_per, SBP_Coef_Module::Define_CSR_Operators(), Deriv2_p, dx, exact_Bruss, grid(), iDeriv2_p, control_variables::Jac_case, jDeriv2_p, neq, SBP_Coef_Module::nnz_D2_per, precision_vars::pi, control_variables::probname, precision_vars::two, vecl, and x.
Referenced by problemsub_mod::problemsub().
subroutine Brusselator_mod::Build_Jac (real(wp),intent(in) dt, real(wp),intent(in) akk, real(wp),dimension(:),intent(in) a, integer,dimension(:),intent(in) ja, integer,dimension(:),intent(in) ia)
Definition at line 298 of file brusselator_2.f90.
References Jacobian_CSR_Mod::aJac, unary_mod::aplsca(), Jacobian_CSR_Mod::iaJac, Jacobian_CSR_Mod::jaJac, and vecl.
Referenced by Brusselator().
subroutine Brusselator_mod::Build_Source_Jac (real(wp),dimension(:),intent(in) vec, real(wp),dimension(4*vecl),intent(out) Source_p, integer,dimension(4*vecl),intent(out) jSource_p, integer,dimension(2*vecl+1),intent(out) iSource_p)
Definition at line 251 of file brusselator_2.f90.
References unary_mod::dperm(), and vecl.
Referenced by Brusselator().
subroutine Brusselator_mod::grid ()
Definition at line 155 of file brusselator_2.f90.
References dx, vecl, x, xL, and xR.
Referenced by Brusselator().
Variable Documentation
real(wp),dimension(10*vecl Brusselator_mod::Deriv2_p)
Definition at line 42 of file brusselator_2.f90.
Referenced by Bruss_dUdt(), and Brusselator().
real(wp) Brusselator_mod::dx
Definition at line 39 of file brusselator_2.f90.
Referenced by Brusselator(), and grid().
real(wp),dimension(vecl*2 Brusselator_mod::exact_Bruss)(eps)
Definition at line 167 of file brusselator_2.f90.
Referenced by Brusselator().
integer,dimension(vecl*2+1 Brusselator_mod::iDeriv2_p)
Definition at line 43 of file brusselator_2.f90.
Referenced by Bruss_dUdt(), and Brusselator().
integer,dimension(10*vecl Brusselator_mod::jDeriv2_p)
Definition at line 41 of file brusselator_2.f90.
Referenced by Bruss_dUdt(), and Brusselator().
integer,parameter Brusselator_mod::neq = 2
Definition at line 35 of file brusselator_2.f90.
Referenced by Brusselator().
integer,parameter Brusselator_mod::vecl = 32
Definition at line 34 of file brusselator_2.f90.
Referenced by Bruss_dUdt(), Brusselator(), Build_Jac(), Build_Source_Jac(), and grid().
real(wp),dimension(vecl) Brusselator_mod::x
Definition at line 38 of file brusselator_2.f90.
Referenced by Brusselator(), and grid().
real(wp),parameter Brusselator_mod::xL = 0.0_wp
Definition at line 36 of file brusselator_2.f90.
Referenced by grid().
real(wp),parameter Brusselator_mod::xR = 1.0_wp
Definition at line 36 of file brusselator_2.f90.
Referenced by grid().