Doxygen Fortran Example: eispack_module Module Reference
eispack_module Module Reference
Functions/Subroutines
subroutine balanc (nm, n, a, low, igh, scale)
subroutine balbak (nm, n, low, igh, scale, m, z)
subroutine cdiv (ar, ai, br, bi, cr, ci)
subroutine elmhes (nm, n, low, igh, a, int)
subroutine eltran (nm, n, low, igh, a, int, z)
real(wp) epslon (x)
subroutine hqr1 (nm, n, low, igh, h, wr, wi, ierr)
subroutine hqr2 (nm, n, low, igh, h, wr, wi, z, ierr)
subroutine hqr (nm, n, low, igh, h, wr, wi, ierr)
subroutine imtqlv (n, d, e, e2, w, ind, ierr, rv1)
subroutine minfit (nm, m, n, a, w, ip, b, ierr, rv1)
subroutine tqlrat (n, d, e2, ierr)
real(wp) pythag (a, b)
subroutine qsortd (x, ind, n)
subroutine qzhes (nm, n, a, b, matz, z)
subroutine qzit (nm, n, a, b, eps1, matz, z, ierr)
subroutine qzval (nm, n, a, b, alfr, alfi, beta, matz, z)
subroutine qzvec (nm, n, a, b, alfr, alfi, beta, z)
subroutine rebak (nm, n, b, dl, m, z)
subroutine reduc (nm, n, a, b, dl, ierr)
subroutine rg (nm, n, a, wr, wi, matz, z, iv1, fv1, ierr)
subroutine rgg (nm, n, a, b, alfr, alfi, beta, matz, z, ierr)
subroutine rs (nm, n, a, w, matz, z, fv1, fv2, ierr)
subroutine rsg (nm, n, a, b, w, matz, z, fv1, fv2, ierr)
subroutine rsm (nm, n, a, w, m, z, fwork, iwork, ierr)
subroutine svd (nm, m, n, a, w, matu, u, matv, v, ierr, rv1)
subroutine tinvit (nm, n, d, e, e2, m, w, ind, z,&ierr, rv1, rv2, rv3, rv4, rv6)
subroutine tql1 (n, d, e, ierr)
subroutine tql2 (nm, n, d, e, z, ierr)
subroutine trbak1 (nm, n, a, e, m, z)
subroutine tred1 (nm, n, a, d, e, e2)
subroutine tred2 (nm, n, a, d, e, z)
subroutine Eigen_Sym (n, AA, RR, EE)
Variables
character(len=*), paramete eispack_module_scm_id)
Function/Subroutine Documentation
subroutine eispack_module::balanc (integer nm, integer n, real(wp),dimension(nm,n) a, integer low, integer igh, real(wp),dimension(n) scale) [private]
Definition at line 31 of file eispack_module.f90.
Referenced by rg().
subroutine eispack_module::balbak (integer nm, integer n, integer low, integer igh, real(wp),dimension(n) scale, integer m, real(wp),dimension(nm,m) z) [private]
Definition at line 200 of file eispack_module.f90.
Referenced by rg().
subroutine eispack_module::cdiv (real(wp) ar, real(wp) ai, real(wp) br, real(wp) bi, real(wp) cr, real(wp) ci) [private]
Definition at line 278 of file eispack_module.f90.
Referenced by hqr2().
subroutine eispack_module::Eigen_Sym (integer,intent(in) n, real(wp),dimension(n,n),intent(in) AA, real(wp),dimension(n,n),intent(out) RR, real(wp),dimension(n),intent(out) EE)
Definition at line 5215 of file eispack_module.f90.
subroutine eispack_module::elmhes (integer nm, integer n, integer low, integer igh, real(wp),dimension(nm,n) a, integer,dimension(igh) int)
Definition at line 297 of file eispack_module.f90.
Referenced by rg().
subroutine eispack_module::eltran (integer nm, integer n, integer low, integer igh, real(wp),dimension(nm,igh) a, integer,dimension(igh) int, real(wp),dimension(nm,n) z)
Definition at line 398 of file eispack_module.f90.
Referenced by rg().
real(wp) eispack_module::epslon (real(wp) x)
Definition at line 479 of file eispack_module.f90.
Referenced by ilut_module::pgmres(), qzit(), tinvit(), and tqlrat().
subroutine eispack_module::hqr (integer nm, integer n, integer low, integer igh, real(wp),dimension(nm,n) h, real(wp),dimension(n) wr, real(wp),dimension(n) wi, integer ierr)
Definition at line 1208 of file eispack_module.f90.
Referenced by rg().
subroutine eispack_module::hqr1 (integer nm, integer n, integer low, integer igh, real(wp),dimension(nm,n) h, real(wp),dimension(n) wr, real(wp),dimension(n) wi, integer ierr) [private]
Definition at line 518 of file eispack_module.f90.
subroutine eispack_module::hqr2 (integer nm, integer n, integer low, integer igh, real(wp),dimension(nm,n) h, real(wp),dimension(n) wr, real(wp),dimension(n) wi, real(wp),dimension(nm,n) z, integer ierr) [private]
Definition at line 756 of file eispack_module.f90.
References cdiv().
Referenced by rg().
subroutine eispack_module::imtqlv (integer n, real(wp),dimension(n) d, real(wp),dimension(n) e, real(wp),dimension(n) e2, real(wp),dimension(n) w, integer,dimension(n) ind, integer ierr, real(wp),dimension(n) rv1) [private]
Definition at line 1446 of file eispack_module.f90.
References pythag().
Referenced by rsm().
subroutine eispack_module::minfit (integer nm, integer m, integer n, real(wp),dimension(nm,n) a, real(wp),dimension(n) w, integer ip, real(wp),dimension(nm,ip) b, integer ierr, real(wp),dimension(n) rv1)
Definition at line 1598 of file eispack_module.f90.
References pythag().
real(wp) eispack_module::pythag (real(wp) a, real(wp) b) [private]
Definition at line 2063 of file eispack_module.f90.
Referenced by imtqlv(), minfit(), svd(), tinvit(), tql1(), tql2(), and tqlrat().
subroutine eispack_module::qsortd (real(wp),dimension(:),intent(in) x, INTEGER,dimension(:),intent(out) ind, INTEGER,intent(in) n)
Definition at line 2086 of file eispack_module.f90.
subroutine eispack_module::qzhes (integer nm, integer n, real(wp),dimension(nm,n) a, real(wp),dimension(nm,n) b, logical matz, real(wp),dimension(nm,n) z) [private]
Definition at line 2290 of file eispack_module.f90.
Referenced by rgg().
subroutine eispack_module::qzit (integer nm, integer n, real(wp),dimension(nm,n) a, real(wp),dimension(nm,n) b, real(wp) eps1, logical matz, real(wp),dimension(nm,n) z, integer ierr) [private]
Definition at line 2489 of file eispack_module.f90.
References epslon().
Referenced by rgg().
subroutine eispack_module::qzval (integer nm, integer n, real(wp),dimension(nm,n) a, real(wp),dimension(nm,n) b, real(wp),dimension(n) alfr, real(wp),dimension(n) alfi, real(wp),dimension(n) beta, logical matz, real(wp),dimension(nm,n) z) [private]
Definition at line 2850 of file eispack_module.f90.
Referenced by rgg().
subroutine eispack_module::qzvec (integer nm, integer n, real(wp),dimension(nm,n) a, real(wp),dimension(nm,n) b, real(wp),dimension(n) alfr, real(wp),dimension(n) alfi, real(wp),dimension(n) beta, real(wp),dimension(nm,n) z) [private]
Definition at line 3130 of file eispack_module.f90.
Referenced by rgg().
subroutine eispack_module::rebak (integer nm, integer n, real(wp),dimension(nm,n) b, real(wp),dimension(n) dl, integer m, real(wp),dimension(nm,m) z) [private]
Definition at line 3381 of file eispack_module.f90.
Referenced by rsg().
subroutine eispack_module::reduc (integer nm, integer n, real(wp),dimension(nm,n) a, real(wp),dimension(nm,n) b, real(wp),dimension(n) dl, integer ierr) [private]
Definition at line 3447 of file eispack_module.f90.
Referenced by rsg().
subroutine eispack_module::rg (integer nm, integer n, real(wp),dimension(nm,n) a, real(wp),dimension(n) wr, real(wp),dimension(n) wi, integer matz, real(wp),dimension(nm,n) z, integer,dimension(n) iv1, real(wp),dimension(n) fv1, integer ierr)
Definition at line 3565 of file eispack_module.f90.
References balanc(), balbak(), elmhes(), eltran(), hqr(), and hqr2().
subroutine eispack_module::rgg (integer nm, integer n, real(wp),dimension(nm,n) a, real(wp),dimension(nm,n) b, real(wp),dimension(n) alfr, real(wp),dimension(n) alfi, real(wp),dimension(n) beta, integer matz, real(wp),dimension(nm,n) z, integer ierr)
Definition at line 3638 of file eispack_module.f90.
References qzhes(), qzit(), qzval(), and qzvec().
subroutine eispack_module::rs (integer nm, integer n, real(wp),dimension(nm,n) a, real(wp),dimension(n) w, integer matz, real(wp),dimension(nm,n) z, real(wp),dimension(n) fv1, real(wp),dimension(n) fv2, integer ierr)
Definition at line 3719 of file eispack_module.f90.
References tql1(), tql2(), tred1(), and tred2().
subroutine eispack_module::rsg (integer nm, integer n, real(wp),dimension(nm,n) a, real(wp),dimension(nm,n) b, real(wp),dimension(n) w, integer matz, real(wp),dimension(nm,n) z, real(wp),dimension(n) fv1, real(wp),dimension(n) fv2, integer ierr) [private]
Definition at line 3781 of file eispack_module.f90.
References rebak(), reduc(), tql2(), tqlrat(), tred1(), and tred2().
subroutine eispack_module::rsm (integer nm, integer n, real(wp),dimension(nm,n) a, real(wp),dimension(n) w, integer m, real(wp),dimension(nm,m) z, real(wp),dimension(1) fwork, integer,dimension(n) iwork, integer ierr) [private]
Definition at line 3847 of file eispack_module.f90.
References imtqlv(), tinvit(), tqlrat(), trbak1(), and tred1().
subroutine eispack_module::svd (integer nm, integer m, integer n, real(wp),dimension(nm,n) a, real(wp),dimension(n) w, logical matu, real(wp),dimension(nm,n) u, logical matv, real(wp),dimension(nm,n) v, integer ierr, real(wp),dimension(n) rv1)
Definition at line 3922 of file eispack_module.f90.
References pythag().
subroutine eispack_module::tinvit (integer nm, integer n, real(wp),dimension(n) d, real(wp),dimension(n) e, real(wp),dimension(n) e2, integer m, real(wp),dimension(m) w, integer,dimension(m) ind, real(wp),dimension(nm,m) z, & ierr, real(wp),dimension(n) rv1, real(wp),dimension(n) rv2, real(wp),dimension(n) rv3, real(wp),dimension(n) rv4, real(wp),dimension(n) rv6) [private]
Definition at line 4286 of file eispack_module.f90.
References epslon(), and pythag().
Referenced by rsm().
subroutine eispack_module::tql1 (integer n, real(wp),dimension(n) d, real(wp),dimension(n) e, integer ierr) [private]
Definition at line 4524 of file eispack_module.f90.
References pythag().
Referenced by rs().
subroutine eispack_module::tql2 (integer nm, integer n, real(wp),dimension(n) d, real(wp),dimension(n) e, real(wp),dimension(nm,n) z, integer ierr) [private]
Definition at line 4662 of file eispack_module.f90.
References pythag().
Referenced by rs(), and rsg().
subroutine eispack_module::tqlrat (integer n, real(wp),dimension(n) d, real(wp),dimension(n) e2, integer ierr) [private]
Definition at line 1930 of file eispack_module.f90.
References epslon(), and pythag().
Referenced by rsg(), and rsm().
subroutine eispack_module::trbak1 (integer nm, integer n, real(wp),dimension(nm,n) a, real(wp),dimension(n) e, integer m, real(wp),dimension(nm,m) z) [private]
Definition at line 4835 of file eispack_module.f90.
Referenced by rsm().
subroutine eispack_module::tred1 (integer nm, integer n, real(wp),dimension(nm,n) a, real(wp),dimension(n) d, real(wp),dimension(n) e, real(wp),dimension(n) e2) [private]
Definition at line 4911 of file eispack_module.f90.
Referenced by rs(), rsg(), and rsm().
subroutine eispack_module::tred2 (integer nm, integer n, real(wp),dimension(nm,n) a, real(wp),dimension(n) d, real(wp),dimension(n) e, real(wp),dimension(nm,n) z) [private]
Definition at line 5049 of file eispack_module.f90.
Referenced by rs(), and rsg().
Variable Documentation
character (len=*),paramete eispack_module::eispack_module_scm_id)
Definition at line 15 of file eispack_module.f90.