Doxygen Fortran Example: Newton Module Reference
Newton Module Reference
Functions/Subroutines
subroutine Newton_Iteration (iprob, L, ep, dt, nveclen, time, aI, icount, k)
logical check_exit (uveciter, k)
real(wp), dimension(size(uvec) Build_Rnewton (ep, dt, time, aI, iprob, L)
subroutine Build_Jac (ep, dt, time, aI, iprob, L)
subroutine LU_solver (Rnewton)
subroutine newt_line_search (iprob, L, ep, dt, nveclen, time, aI, icount, k)
subroutine QR_decomp (mat, nveclen, Rnewton)
real(wp), dimension(size(mat(:, 1) Mat_invert (mat)
subroutine Convert_to_CSR (a)
Function/Subroutine Documentation
subroutine Newton::Build_Jac (real(wp),intent(in) ep, real(wp),intent(in) dt, real(wp),intent(in) time, real(wp),intent(in) aI, integer,intent(in) iprob, integer,intent(in) L)
Definition at line 148 of file Newton.f90.
References problemsub_mod::problemsub().
Referenced by newt_line_search(), and Newton_Iteration().
real(wp),dimension(size(uvec) Newton::Build_Rnewton (real(wp),intent(in) ep, real(wp),intent(in) dt, real(wp),intent(in) time, real(wp),intent(in) aI, integer,intent(in) iprob, integer,intent(in) L)
Definition at line 127 of file Newton.f90.
References problemsub_mod::problemsub(), control_variables::resI, and control_variables::usum.
Referenced by newt_line_search(), and Newton_Iteration().
logical Newton::check_exit (real(wp),dimension(:),intent(in) uveciter, integer,intent(in) k)
Definition at line 106 of file Newton.f90.
References control_variables::tol, and control_variables::uvec.
Referenced by Newton_Iteration().
subroutine Newton::Convert_to_CSR (real(wp),dimension(:,:),intent(in) a) [private]
Definition at line 420 of file Newton.f90.
References Jacobian_CSR_Mod::aJac, Jacobian_CSR_Mod::Allocate_Jac_CSR_Storage(), Jacobian_CSR_Mod::iaJac, and Jacobian_CSR_Mod::jaJac.
Referenced by Newton_Iteration().
subroutine Newton::LU_solver (real(wp),dimension(:) Rnewton)
Definition at line 169 of file Newton.f90.
References Jacobian_CSR_Mod::aJac, Jacobian_CSR_Mod::aLUJac, Jacobian_CSR_Mod::iaJac, ilut_module::ilutp(), Jacobian_CSR_Mod::jaJac, Jacobian_CSR_Mod::jLUJac, Jacobian_CSR_Mod::jUJac, ilut_module::lusol(), and control_variables::uvec.
Referenced by Newton_Iteration().
real(wp),dimension(size(mat(:,1) Newton::Mat_invert (real(wp),dimension(:,:),intent(in) mat)
Definition at line 285 of file Newton.f90.
Referenced by newt_line_search(), and Newton_Iteration().
subroutine Newton::newt_line_search (integer,intent(in) iprob, integer,intent(in) L, real(wp),intent(in) ep, real(wp),intent(in) dt, integer,intent(in) nveclen, real(wp),intent(in) time, real(wp),intent(in) aI, integer,intent(inout) icount, integer,intent(inout) k)
Definition at line 197 of file Newton.f90.
References Build_Jac(), Build_Rnewton(), Mat_invert(), control_variables::uvec, and control_variables::xjac.
Referenced by Newton_Iteration().
subroutine Newton::Newton_Iteration (integer,intent(in) iprob, integer,intent(in) L, real(wp),intent(in) ep, real(wp),intent(in) dt, integer,intent(in) nveclen, real(wp),intent(in) time, real(wp),intent(in) aI, integer,intent(inout) icount, integer,intent(out) k)
Definition at line 25 of file Newton.f90.
References Build_Jac(), Build_Rnewton(), check_exit(), Convert_to_CSR(), LU_solver(), Mat_invert(), newt_line_search(), QR_decomp(), control_variables::usum, control_variables::uvec, and control_variables::xjac.
Referenced by test_cases().
subroutine Newton::QR_decomp (real(wp),dimension(:,:),intent(inout) mat, integer,intent(in) nveclen, real(wp),dimension(:),intent(inout) Rnewton)
Definition at line 261 of file Newton.f90.
References QR_Module::qrdcmp(), QR_Module::qrsolv(), and control_variables::uvec.
Referenced by Newton_Iteration().