Doxygen Fortran Example: QR_Module Module Reference
QR_Module Module Reference
Functions/Subroutines
subroutine qrdcmp (a, n, np, c, d, sing)
subroutine qrsolv (a, n, np, c, d, b)
subroutine rsolv (a, n, np, d, b)
Function/Subroutine Documentation
subroutine QR_Module::qrdcmp (REAL(wp),dimension(np,np),intent(inout) a, INTEGER,intent(in) n, INTEGER,intent(in) np, REAL(wp),dimension(n),intent(out) c, REAL(wp),dimension(n),intent(out) d, LOGICAL,intent(out) sing)
Definition at line 21 of file QR_Module.f90.
Referenced by Newton::QR_decomp().
subroutine QR_Module::qrsolv (REAL(wp),dimension(np,np),intent(inout) a, INTEGER,intent(in) n, INTEGER,intent(in) np, REAL(wp),dimension(n),intent(in) c, REAL(wp),dimension(n),intent(in) d, REAL(wp),dimension(n),intent(inout) b)
Definition at line 80 of file QR_Module.f90.
References rsolv().
Referenced by Newton::QR_decomp().
subroutine QR_Module::rsolv (REAL(wp),dimension(np,np),intent(inout) a, INTEGER,intent(in) n, INTEGER,intent(in) np, REAL(wp),dimension(n),intent(in) d, REAL(wp),dimension(n),intent(inout) b) [private]
Definition at line 113 of file QR_Module.f90.
Referenced by qrsolv().