Doxygen Fortran Example: output_module Module Reference
output_module Module Reference
Functions/Subroutines
subroutine set_file_loc ()
subroutine create_file_paths ()
subroutine output_names ()
subroutine init_output_files (neq, ep)
subroutine output_conv_stiff (nveclen, neq, epsave)
subroutine output_terminal_iteration (cost, mwt, ep, nveclen, neq)
subroutine output_terminal_final (icount, jcount, stageE, stageI, maxiter)
subroutine output_conv_error (cost, nveclen, neq)
Variables
character(len=80) fileloc
character(len=4), parameter ext
Function/Subroutine Documentation
subroutine output_module::create_file_paths ()
Definition at line 44 of file output_module.f90.
References fileloc, and set_file_loc().
Referenced by test_cases().
subroutine output_module::init_output_files (integer,intent(in) neq, real(wp),intent(in) ep)
Definition at line 69 of file output_module.f90.
References runge_kutta::casename, ext, fileloc, and control_variables::probname.
Referenced by test_cases().
subroutine output_module::output_conv_error (real(wp),intent(in) cost, integer,intent(in) nveclen, integer,intent(in) neq)
Definition at line 219 of file output_module.f90.
References control_variables::errvecT, control_variables::uexact, and control_variables::uvec.
Referenced by test_cases().
subroutine output_module::output_conv_stiff (integer,intent(in) nveclen, integer,intent(in) neq, real(wp),dimension(:),intent(in) epsave)
Definition at line 94 of file output_module.f90.
References runge_kutta::casename, ext, fileloc, control_variables::jactual, and control_variables::probname.
Referenced by test_cases().
subroutine output_module::output_names ()
Definition at line 56 of file output_module.f90.
References runge_kutta::casename, and control_variables::probname.
Referenced by test_cases().
subroutine output_module::output_terminal_final (integer,intent(in) icount, integer,intent(in) jcount, real(wp),dimension(:),intent(inout) stageE, real(wp),dimension(:),intent(inout) stageI, real(wp),dimension(:),intent(inout) maxiter)
Definition at line 194 of file output_module.f90.
References runge_kutta::ns.
Referenced by test_cases().
subroutine output_module::output_terminal_iteration (real(wp),dimension(:),intent(in) cost, integer,intent(in) mwt, real(wp),intent(in) ep, integer,intent(in) nveclen, integer,intent(in) neq)
Definition at line 133 of file output_module.f90.
References control_variables::b, control_variables::dt_error_tol, control_variables::error, control_variables::errorL2, control_variables::errorP, and poly_fit_Mod::fit().
Referenced by test_cases().
subroutine output_module::set_file_loc () [private]
Definition at line 32 of file output_module.f90.
References runge_kutta::casename, fileloc, and control_variables::probname.
Referenced by create_file_paths().
Variable Documentation
character(len=4),parameter output_module::ext
Definition at line 26 of file output_module.f90.
Referenced by init_output_files(), and output_conv_stiff().
character(len=80) output_module::fileloc
Definition at line 25 of file output_module.f90.
Referenced by create_file_paths(), init_output_files(), output_conv_stiff(), and set_file_loc().