Doxygen Fortran Example: Jacobian_CSR_Mod Module Reference
Jacobian_CSR_Mod Module Reference
Functions/Subroutines
subroutine Allocate_Jac_CSR_Storage (nJac, nnz)
Variables
integer, dimension(:), allocatable iaJac
integer, dimension(:), allocatable jaJac
integer, dimension(:), allocatable jUJac
integer, dimension(:), allocatable jLUJac
integer, dimension(:), allocatable iw
real(wp), dimension(:), allocatable aJac
real(wp), dimension(:), allocatable aLUJac
Function/Subroutine Documentation
subroutine Jacobian_CSR_Mod::Allocate_Jac_CSR_Storage (integer,intent(in) nJac, integer,intent(in) nnz)
Definition at line 22 of file Jacobian_CSR_Mod.f90.
References aJac, aLUJac, iaJac, iw, jaJac, jLUJac, and jUJac.
Referenced by Boscarino31_Mod::Boscarino31(), Broadwell_Mod::Broadwell(), Brusselator_mod::Brusselator(), Burgers_Module::Burgers(), and Newton::Convert_to_CSR().
Variable Documentation
real(wp),dimension(:),allocatable Jacobian_CSR_Mod::aJac
Definition at line 17 of file Jacobian_CSR_Mod.f90.
Referenced by Allocate_Jac_CSR_Storage(), Boscarino31_Mod::Bosc_Jac(), Broadwell_Mod::Broadwell_Add_Diag_Jac(), Burgers_Module::Build_Jac(), Brusselator_mod::Build_Jac(), Newton::Convert_to_CSR(), control_variables::deallocate_vars(), and Newton::LU_solver().
real(wp),dimension(:),allocatable Jacobian_CSR_Mod::aLUJac
Definition at line 17 of file Jacobian_CSR_Mod.f90.
Referenced by Allocate_Jac_CSR_Storage(), control_variables::deallocate_vars(), and Newton::LU_solver().
integer,dimension(:),allocatable Jacobian_CSR_Mod::iaJac
Definition at line 16 of file Jacobian_CSR_Mod.f90.
Referenced by Allocate_Jac_CSR_Storage(), Boscarino31_Mod::Bosc_Jac(), Broadwell_Mod::Broadwell_Add_Diag_Jac(), Burgers_Module::Build_Jac(), Brusselator_mod::Build_Jac(), Newton::Convert_to_CSR(), control_variables::deallocate_vars(), and Newton::LU_solver().
integer,dimension(:),allocatable Jacobian_CSR_Mod::iw
Definition at line 16 of file Jacobian_CSR_Mod.f90.
Referenced by Allocate_Jac_CSR_Storage(), and control_variables::deallocate_vars().
integer,dimension(:),allocatable Jacobian_CSR_Mod::jaJac
Definition at line 16 of file Jacobian_CSR_Mod.f90.
Referenced by Allocate_Jac_CSR_Storage(), Boscarino31_Mod::Bosc_Jac(), Broadwell_Mod::Broadwell_Add_Diag_Jac(), Burgers_Module::Build_Jac(), Brusselator_mod::Build_Jac(), Newton::Convert_to_CSR(), control_variables::deallocate_vars(), and Newton::LU_solver().
integer,dimension(:),allocatable Jacobian_CSR_Mod::jLUJac
Definition at line 16 of file Jacobian_CSR_Mod.f90.
Referenced by Allocate_Jac_CSR_Storage(), control_variables::deallocate_vars(), and Newton::LU_solver().
integer,dimension(:),allocatable Jacobian_CSR_Mod::jUJac
Definition at line 16 of file Jacobian_CSR_Mod.f90.
Referenced by Allocate_Jac_CSR_Storage(), control_variables::deallocate_vars(), and Newton::LU_solver().