Doxygen Fortran Example: Broadwell_Mod Module Reference
Broadwell_Mod Module Reference
Functions/Subroutines
subroutine Broadwell (nveclen, eq, ep, dt, tfinal, iDT, resE_vec, resI_vec, akk)
subroutine grid ()
subroutine exact_Broadwell (u, ep)
subroutine Broadwell_dUdt (u, dudt_D1, dudt_Source, ep)
subroutine Broadwell_Build_Spatial_Jac (a, ja, ia)
subroutine Broadwell_Build_Source_Jac (ep, u, a, ja, ia)
subroutine Broadwell_Add_Diag_Jac (dt, akk, a, ja, ia)
Variables
integer, parameter nx = 32
integer, parameter neq = 3
integer, parameter vecl = nx * neq
real(wp), parameter Length = 20.0_wp
real(wp), parameter xL = -10.0_wp
real(wp), parameter xR = +10.0_wp
real(wp), parameter a_u1 = + 0.3_wp
real(wp), parameter a_u2 = + 0.1_wp
real(wp), dimension(nx) x
real(wp) dx
integer, dimension(vecl+1) iSource_p
integer, dimension(vecl+1) iDeriv_comb_p
integer, dimension(vecl+1) iwrk_Jac
integer, dimension(4 *vecl jDeriv_comb_p)
integer, dimension(5 *vecl jwrk_Jac)
integer, dimension(vecl) jSource_p
real(wp), dimension(4 *vecl Deriv_comb_p)
real(wp), dimension(5 *vecl wrk_Jac)
real(wp), dimension(vecl) Source_p
logical update_RHS
logical update_Jac
Function/Subroutine Documentation
subroutine Broadwell_Mod::Broadwell (integer,intent(out) nveclen, integer,intent(out) eq, real(wp),intent(in) ep, real(wp),intent(inout) dt, real(wp),intent(out) tfinal, integer,intent(in) iDT, real(wp),dimension(vecl),intent(out) resE_vec, real(wp),dimension(vecl),intent(out) resI_vec, real(wp),intent(in) akk)
Definition at line 59 of file Broadwell_mod.f90.
References a_u1, a_u2, Jacobian_CSR_Mod::Allocate_Jac_CSR_Storage(), unary_mod::aplb(), Broadwell_Add_Diag_Jac(), Broadwell_Build_Source_Jac(), Broadwell_Build_Spatial_Jac(), Broadwell_dUdt(), SBP_Coef_Module::D1_per, SBP_Coef_Module::Define_CSR_Operators(), Deriv_comb_p, dx, exact_Broadwell(), grid(), iDeriv_comb_p, iSource_p, iwrk_Jac, control_variables::Jac_case, jDeriv_comb_p, jSource_p, jwrk_Jac, Length, neq, nx, precision_vars::pi, control_variables::probname, Source_p, update_Jac, vecl, wrk_Jac, and x.
Referenced by problemsub_mod::problemsub().
subroutine Broadwell_Mod::Broadwell_Add_Diag_Jac (real(wp),intent(in) dt, real(wp),intent(in) akk, real(wp),dimension(:),intent(in) a, integer,dimension(:),intent(in) ja, integer,dimension(:),intent(in) ia) [private]
Definition at line 367 of file Broadwell_mod.f90.
References Jacobian_CSR_Mod::aJac, unary_mod::aplsca(), Jacobian_CSR_Mod::iaJac, Jacobian_CSR_Mod::jaJac, and vecl.
Referenced by Broadwell().
subroutine Broadwell_Mod::Broadwell_Build_Source_Jac (real(wp),intent(in) ep, real(wp),dimension(vecl),intent(in) u, real(wp),dimension(vecl),intent(out) a, integer,dimension(vecl),intent(out) ja, integer,dimension(vecl+1),intent(out) ia)
Definition at line 329 of file Broadwell_mod.f90.
References neq, nx, and vecl.
Referenced by Broadwell().
subroutine Broadwell_Mod::Broadwell_Build_Spatial_Jac (real(wp),dimension(nnz_d1_per),intent(out) a, integer,dimension(nnz_d1_per),intent(out) ja, integer,dimension(vecl+1),intent(out) ia)
Definition at line 277 of file Broadwell_mod.f90.
References SBP_Coef_Module::D1_per, unary_mod::dperm(), SBP_Coef_Module::jD1_per, SBP_Coef_Module::nnz_D1_per, nx, and vecl.
Referenced by Broadwell().
subroutine Broadwell_Mod::Broadwell_dUdt (real(wp),dimension(vecl),intent(in) u, real(wp),dimension(vecl),intent(out) dudt_D1, real(wp),dimension(vecl),intent(out) dudt_Source, real(wp),intent(in) ep) [private]
Definition at line 237 of file Broadwell_mod.f90.
References matvec_module::amux(), SBP_Coef_Module::D1_per, SBP_Coef_Module::iD1_per, SBP_Coef_Module::jD1_per, nx, and vecl.
Referenced by Broadwell().
subroutine Broadwell_Mod::exact_Broadwell (real(wp),dimension(vecl),intent(out) u, real(wp),intent(in) ep) [private]
Definition at line 207 of file Broadwell_mod.f90.
References vecl.
Referenced by Broadwell().
subroutine Broadwell_Mod::grid ()
Definition at line 195 of file Broadwell_mod.f90.
References dx, nx, x, xL, and xR.
Referenced by Broadwell().
Variable Documentation
real(wp),parameter Broadwell_Mod::a_u1 = + 0.3_wp
Definition at line 31 of file Broadwell_mod.f90.
Referenced by Broadwell().
real(wp),parameter Broadwell_Mod::a_u2 = + 0.1_wp
Definition at line 32 of file Broadwell_mod.f90.
Referenced by Broadwell().
real(wp),dimension(4*vecl Broadwell_Mod::Deriv_comb_p)
Definition at line 42 of file Broadwell_mod.f90.
Referenced by Broadwell().
real(wp) Broadwell_Mod::dx
Definition at line 35 of file Broadwell_mod.f90.
Referenced by Broadwell(), and grid().
integer,dimension(vecl+1) Broadwell_Mod::iDeriv_comb_p
Definition at line 37 of file Broadwell_mod.f90.
Referenced by Broadwell().
integer,dimension(vecl+1) Broadwell_Mod::iSource_p
Definition at line 37 of file Broadwell_mod.f90.
Referenced by Broadwell().
integer,dimension(vecl+1) Broadwell_Mod::iwrk_Jac
Definition at line 37 of file Broadwell_mod.f90.
Referenced by Broadwell().
integer,dimension(4*vecl Broadwell_Mod::jDeriv_comb_p)
Definition at line 38 of file Broadwell_mod.f90.
Referenced by Broadwell().
integer,dimension(vecl) Broadwell_Mod::jSource_p
Definition at line 40 of file Broadwell_mod.f90.
Referenced by Broadwell().
integer,dimension(5*vecl Broadwell_Mod::jwrk_Jac)
Definition at line 39 of file Broadwell_mod.f90.
Referenced by Broadwell().
real(wp),parameter Broadwell_Mod::Length = 20.0_wp
Definition at line 28 of file Broadwell_mod.f90.
Referenced by Broadwell().
integer,parameter Broadwell_Mod::neq = 3
Definition at line 24 of file Broadwell_mod.f90.
Referenced by Broadwell(), and Broadwell_Build_Source_Jac().
integer,parameter Broadwell_Mod::nx = 32
Definition at line 23 of file Broadwell_mod.f90.
Referenced by Broadwell(), Broadwell_Build_Source_Jac(), Broadwell_Build_Spatial_Jac(), Broadwell_dUdt(), and grid().
real(wp),dimension(vecl) Broadwell_Mod::Source_p
Definition at line 45 of file Broadwell_mod.f90.
Referenced by Broadwell().
logical Broadwell_Mod::update_Jac
Definition at line 46 of file Broadwell_mod.f90.
Referenced by Broadwell().
logical Broadwell_Mod::update_RHS
Definition at line 46 of file Broadwell_mod.f90.
integer,parameter Broadwell_Mod::vecl = nx * neq
Definition at line 26 of file Broadwell_mod.f90.
Referenced by Broadwell(), Broadwell_Add_Diag_Jac(), Broadwell_Build_Source_Jac(), Broadwell_Build_Spatial_Jac(), Broadwell_dUdt(), and exact_Broadwell().
real(wp),dimension(5*vecl Broadwell_Mod::wrk_Jac)
Definition at line 43 of file Broadwell_mod.f90.
Referenced by Broadwell().
real(wp),dimension(nx) Broadwell_Mod::x
Definition at line 34 of file Broadwell_mod.f90.
Referenced by Broadwell(), and grid().
real(wp),parameter Broadwell_Mod::xL = -10.0_wp
Definition at line 29 of file Broadwell_mod.f90.
Referenced by grid().
real(wp),parameter Broadwell_Mod::xR = +10.0_wp
Definition at line 30 of file Broadwell_mod.f90.
Referenced by grid().