Doxygen Fortran Example: ilut_module Module Reference
ilut_module Module Reference
Functions/Subroutines
subroutine ilut (n, a, ja, ia, lfil, droptol, alu, jlu, ju, iwk, w, jw, ierr)
subroutine ilutp (n, a, ja, ia, lfil, droptol, permtol, mbloc, alu,&jlu, ju, iwk, w, jw, iperm, ierr)
subroutine ilud (n, a, ja, ia, alph, tol, alu, jlu, ju, iwk, w, jw, ierr)
subroutine iludp (n, a, ja, ia, alph, droptol, permtol, mbloc, alu,&jlu, ju, iwk, w, jw, iperm, ierr)
subroutine iluk (n, a, ja, ia, lfil, alu, jlu, ju, levs, iwk, w, jw, ierr)
subroutine ilu0 (n, a, ja, ia, alu, jlu, ju, iw, ierr)
subroutine milu0 (n, a, ja, ia, alu, jlu, ju, iw, ierr)
subroutine ilu0_csr (n, nnz, a, ja, ia, iau, aI, jaI, iaI, iauI, iw, ierr)
subroutine pgmres (n, im, rhs, sol, vv, eps, maxits, iout,&aa, ja, ia, alu, jlu, ju, ierr)
subroutine lusol (n, y, x, alu, jlu, ju)
subroutine lusol_M_rhs (n, m, y, x, alu, jlu, ju)
subroutine B_lusol (n, neq, nnz, y, x, alu, jlu, ju)
subroutine lusol_csr (n, y, x, a, ja, ia, iau)
subroutine lutsol (n, y, x, alu, jlu, ju)
subroutine qsplit (a, ind, n, ncut)
subroutine msrcsr (n, a, ja, ao, jao, iao, iauo, wk, iwk)
Function/Subroutine Documentation
subroutine ilut_module::B_lusol (integer,intent(in) n, integer,intent(in) neq, integer,intent(in) nnz, real(wp),dimension(neq,nnz),intent(in) y, real(wp),dimension(neq,nnz),intent(out) x, real(wp),dimension(neq,neq,nnz),intent(in) alu, integer,dimension(*),intent(in) jlu, integer,dimension(*),intent(in) ju) [private]
Definition at line 2614 of file ilut_module.f90.
subroutine ilut_module::ilu0 (integer,intent(in) n, real(wp),dimension(*),intent(in) a, integer,dimension(*),intent(in) ja, integer,dimension(*),intent(in) ia, real(wp),dimension(*),intent(out) alu, integer,dimension(*),intent(out) jlu, integer,dimension(*),intent(out) ju, integer,dimension(*),intent(inout) iw, integer,intent(out) ierr)
Definition at line 1811 of file ilut_module.f90.
subroutine ilut_module::ilu0_csr (integer,intent(in) n, integer,intent(in) nnz, real(wp),dimension(*),intent(in) a, integer,dimension(*),intent(in) ja, integer,dimension(*),intent(in) ia, integer,dimension(*),intent(in) iau, real(wp),dimension(*),intent(out) aI, integer,dimension(*),intent(out) jaI, integer,dimension(*),intent(out) iaI, integer,dimension(*),intent(out) iauI, integer,dimension(*),intent(inout) iw, integer,intent(out) ierr)
Definition at line 2089 of file ilut_module.f90.
subroutine ilut_module::ilud (integer n, real(wp),dimension(*) a, integer,dimension(*) ja, integer,dimension(n+1) ia, real(wp) alph, real(wp) tol, real(wp),dimension(*) alu, integer,dimension(*) jlu, integer,dimension(n) ju, integer iwk, real(wp),dimension(2*n) w, integer,dimension(2*n) jw, integer ierr)
Definition at line 798 of file ilut_module.f90.
subroutine ilut_module::iludp (integer n, real(wp),dimension(*) a, integer,dimension(*) ja, integer,dimension(n+1) ia, real(wp) alph, real(wp) droptol, real(wp) permtol, integer mbloc, real(wp),dimension(*) alu, &,dimension(*) jlu, integer,dimension(n) ju, integer iwk, real(wp),dimension(2*n) w, integer,dimension(2*n) jw, integer,dimension(2*n) iperm, integer ierr)
Definition at line 1129 of file ilut_module.f90.
subroutine ilut_module::iluk (integer n, real(wp),dimension(*) a, integer,dimension(*) ja, integer,dimension(n+1) ia, integer lfil, real(wp),dimension(*) alu, integer,dimension(*) jlu, integer,dimension(n) ju, integer,dimension(*) levs, integer iwk, real(wp),dimension(n) w, integer,dimension(3*n) jw, integer ierr)
Definition at line 1501 of file ilut_module.f90.
subroutine ilut_module::ilut (integer,intent(in) n, real(wp),dimension(*),intent(in) a, integer,dimension(*),intent(in) ja, integer,dimension(n+1),intent(in) ia, integer,intent(in) lfil, real(wp),intent(in) droptol, real(wp),dimension(*),intent(inout) alu, integer,dimension(*),intent(inout) jlu, integer,dimension(n),intent(inout) ju, integer,intent(in) iwk, real(wp),dimension(n+1),intent(inout) w, integer,dimension(2*n),intent(inout) jw, integer,intent(out) ierr)
Definition at line 55 of file ilut_module.f90.
References qsplit().
subroutine ilut_module::ilutp (integer n, real(wp),dimension(*) a, integer,dimension(*) ja, integer,dimension(n+1) ia, integer lfil, real(wp) droptol, real(wp) permtol, integer mbloc, real(wp),dimension(*) alu, &,dimension(*) jlu, integer,dimension(n) ju, integer iwk, real(wp),dimension(n+1) w, integer,dimension(2*n) jw, integer,dimension(2*n) iperm, integer ierr)
Definition at line 398 of file ilut_module.f90.
References qsplit().
Referenced by Newton::LU_solver().
subroutine ilut_module::lusol (integer,intent(in) n, real(wp),dimension(*),intent(in) y, real(wp),dimension(*),intent(out) x, real(wp),dimension(*),intent(in) alu, integer,dimension(*),intent(in) jlu, integer,dimension(*),intent(in) ju)
Definition at line 2494 of file ilut_module.f90.
Referenced by Newton::LU_solver(), and pgmres().
subroutine ilut_module::lusol_csr (integer,intent(in) n, real(wp),dimension(*),intent(in) y, real(wp),dimension(*),intent(out) x, real(wp),dimension(*),intent(in) a, integer,dimension(*),intent(in) ja, integer,dimension(*),intent(in) ia, integer,dimension(*),intent(in) iau)
Definition at line 2700 of file ilut_module.f90.
subroutine ilut_module::lusol_M_rhs (integer,intent(in) n, integer,intent(in) m, real(wp),dimension(m,n),intent(in) y, real(wp),dimension(m,n),intent(out) x, real(wp),dimension(*),intent(in) alu, integer,dimension(*),intent(in) jlu, integer,dimension(*),intent(in) ju)
Definition at line 2553 of file ilut_module.f90.
subroutine ilut_module::lutsol (integer n, real(wp),dimension(n) y, real(wp),dimension(n) x, real(wp),dimension(*) alu, integer,dimension(*) jlu, integer,dimension(*) ju) [private]
Definition at line 2765 of file ilut_module.f90.
subroutine ilut_module::milu0 (integer,intent(in) n, real(wp),dimension(*),intent(in) a, integer,dimension(*),intent(in) ja, integer,dimension(*),intent(in) ia, real(wp),dimension(*),intent(out) alu, integer,dimension(*),intent(out) jlu, integer,dimension(*),intent(out) ju, integer,dimension(*),intent(inout) iw, integer,intent(out) ierr) [private]
Definition at line 1951 of file ilut_module.f90.
subroutine ilut_module::msrcsr (integer,intent(in) n, real(wp),dimension(*) a, integer,dimension(*) ja, real(wp),dimension(*) ao, integer,dimension(*) jao, integer,dimension(n+1) iao, integer,dimension(n) iauo, real(wp),dimension(n) wk, integer,dimension(n+1) iwk)
Definition at line 2883 of file ilut_module.f90.
subroutine ilut_module::pgmres (integer n, integer im, real(wp),dimension(n) rhs, real(wp),dimension(n) sol, real(wp),dimension(n,*) vv, real(wp),intent(in) eps, integer maxits, integer iout, &,dimension(*) aa, integer,dimension(*) ja, integer,dimension(n+1) ia, real(wp),dimension(*) alu, integer,dimension(*) jlu, integer,dimension(n) ju, integer ierr) [private]
Definition at line 2240 of file ilut_module.f90.
References matvec_module::amux(), blas_module::daxpy(), blas_module::ddot(), blas_module::dnrm2(), eispack_module::epslon(), and lusol().
subroutine ilut_module::qsplit (real(wp),dimension(n) a, integer,dimension(n) ind, integer n, integer ncut) [private]
Definition at line 2820 of file ilut_module.f90.
Referenced by ilut(), and ilutp().