Doxygen Fortran Example: precision_vars Module Reference
precision_vars Module Reference
Functions/Subroutines
real(wp) magnitude (xin)
real(wp) determinant3 (Pmat)
subroutine get_unit (iunit)
Variables
integer, parameter dp = kind(1.d0)
integer, parameter sp = kind(1.e0)
integer, parameter wp = dp
integer, parameter prec = dp
real(wp), parameter dzero = 0.0d0
real(wp), parameter zero = 0.0_wp
real(wp), parameter one = 1.0_wp
real(wp), parameter two = 2.0_wp
real(wp), parameter three = 3.0_wp
real(wp), parameter four = 4.0_wp
real(wp), parameter five = 5.0_wp
real(wp), parameter six = 6.0_wp
real(wp), parameter seven = 7.0_wp
real(wp), parameter eight = 8.0_wp
real(wp), parameter nine = 9.0_wp
real(wp), parameter ten = 10._wp
real(wp), parameter half = 0.5_wp
real(wp), parameter third = 1.0_wp/3.0_wp
real(wp), parameter twothird = 2.0_wp/3.0_wp
real(wp), parameter fourth = 1.0_wp/4.0_wp
real(wp), parameter fifth = 1.0_wp/5.0_wp
real(wp), parameter sixth = 1.0_wp/6.0_wp
real(wp), parameter seventh = 1.0_wp/7.0_wp
real(wp), parameter eigth = 1.0_wp/8.0_wp
real(wp), parameter ninth = 1.0_wp/9.0_wp
real(wp), parameter tenth = 1.0_wp/10._wp
real(wp), parameter small = 1.0e-10_wp
real(wp), parameter large = 1.0e05_wp
real(wp), parameter realsmall = 1.d-20
real(wp), parameter big = 1.d10
real(wp), parameter realbig = 1.d20
real(wp), parameter pi = 3.1415926535897932384626433832795028841971693993751058209749_wp
Function/Subroutine Documentation
real(wp) precision_vars::determinant3 (real(wp),dimension(3,3),intent(in) Pmat) [private]
Definition at line 67 of file precision_vars.f90.
subroutine precision_vars::get_unit (integer iunit) [private]
Definition at line 82 of file precision_vars.f90.
real(wp) precision_vars::magnitude (real(wp),dimension(:),intent(in) xin) [private]
Definition at line 56 of file precision_vars.f90.
Variable Documentation
real(wp),parameter precision_vars::big = 1.d10
Definition at line 48 of file precision_vars.f90.
integer,parameter precision_vars::dp = kind(1.d0)
Definition at line 14 of file precision_vars.f90.
real(wp),parameter precision_vars::dzero = 0.0d0
Definition at line 24 of file precision_vars.f90.
real(wp),parameter precision_vars::eight = 8.0_wp
Definition at line 33 of file precision_vars.f90.
real(wp),parameter precision_vars::eigth = 1.0_wp/8.0_wp
Definition at line 43 of file precision_vars.f90.
real(wp),parameter precision_vars::fifth = 1.0_wp/5.0_wp
Definition at line 40 of file precision_vars.f90.
real(wp),parameter precision_vars::five = 5.0_wp
Definition at line 30 of file precision_vars.f90.
real(wp),parameter precision_vars::four = 4.0_wp
Definition at line 29 of file precision_vars.f90.
real(wp),parameter precision_vars::fourth = 1.0_wp/4.0_wp
Definition at line 39 of file precision_vars.f90.
real(wp),parameter precision_vars::half = 0.5_wp
Definition at line 36 of file precision_vars.f90.
Referenced by Burgers_Module::Burgers_dUdt().
real(wp),parameter precision_vars::large = 1.0e05_wp
Definition at line 47 of file precision_vars.f90.
real(wp),parameter precision_vars::nine = 9.0_wp
Definition at line 34 of file precision_vars.f90.
real(wp),parameter precision_vars::ninth = 1.0_wp/9.0_wp
Definition at line 44 of file precision_vars.f90.
real(wp),parameter precision_vars::one = 1.0_wp
Definition at line 26 of file precision_vars.f90.
real(wp),parameter precision_vars::pi = 3.1415926535897932384626433832795028841971693993751058209749_wp
Definition at line 49 of file precision_vars.f90.
Referenced by Boscarino31_Mod::Boscarino31(), Broadwell_Mod::Broadwell(), Brusselator_mod::Brusselator(), and Pureschi_mod::Pureschi().
integer,parameter precision_vars::prec = dp
Definition at line 21 of file precision_vars.f90.
real(wp),parameter precision_vars::realbig = 1.d20
Definition at line 48 of file precision_vars.f90.
real(wp),parameter precision_vars::realsmall = 1.d-20
Definition at line 48 of file precision_vars.f90.
real(wp),parameter precision_vars::seven = 7.0_wp
Definition at line 32 of file precision_vars.f90.
real(wp),parameter precision_vars::seventh = 1.0_wp/7.0_wp
Definition at line 42 of file precision_vars.f90.
real(wp),parameter precision_vars::six = 6.0_wp
Definition at line 31 of file precision_vars.f90.
real(wp),parameter precision_vars::sixth = 1.0_wp/6.0_wp
Definition at line 41 of file precision_vars.f90.
real(wp),parameter precision_vars::small = 1.0e-10_wp
Definition at line 46 of file precision_vars.f90.
integer,parameter precision_vars::sp = kind(1.e0)
Definition at line 16 of file precision_vars.f90.
real(wp),parameter precision_vars::ten = 10._wp
Definition at line 35 of file precision_vars.f90.
real(wp),parameter precision_vars::tenth = 1.0_wp/10._wp
Definition at line 45 of file precision_vars.f90.
real(wp),parameter precision_vars::third = 1.0_wp/3.0_wp
Definition at line 37 of file precision_vars.f90.
Referenced by Burgers_Module::Build_Jac(), and Burgers_Module::Burgers_dUdt().
real(wp),parameter precision_vars::three = 3.0_wp
Definition at line 28 of file precision_vars.f90.
real(wp),parameter precision_vars::two = 2.0_wp
Definition at line 27 of file precision_vars.f90.
Referenced by Boscarino31_Mod::Boscarino31(), and Brusselator_mod::Brusselator().
real(wp),parameter precision_vars::twothird = 2.0_wp/3.0_wp
Definition at line 38 of file precision_vars.f90.
Referenced by Burgers_Module::Build_Jac(), and Burgers_Module::Burgers_dUdt().
integer,parameter precision_vars::wp = dp
Definition at line 19 of file precision_vars.f90.
real(wp),parameter precision_vars::zero = 0.0_wp
Definition at line 25 of file precision_vars.f90.