Doxygen Fortran Example: Stage_value_module Module Reference
Stage_value_module Module Reference
Functions/Subroutines
subroutine Stage_Value_Predictor (ipred, L, ktime)
subroutine Stage_Value_Predictor1 (L)
subroutine Stage_Value_Predictor2 (L, ktime)
real(wp) xnorm (vec1, vec2)
Function/Subroutine Documentation
subroutine Stage_value_module::Stage_Value_Predictor (integer,intent(in) ipred, integer,intent(in) L, integer,intent(in) ktime)
Definition at line 23 of file Stage_Value_module.f90.
References Stage_Value_Predictor1(), and Stage_Value_Predictor2().
Referenced by test_cases().
subroutine Stage_value_module::Stage_Value_Predictor1 (integer,intent(in) L) [private]
Definition at line 37 of file Stage_Value_module.f90.
References runge_kutta::ns, control_variables::predvec, and control_variables::ustage.
Referenced by Stage_Value_Predictor().
subroutine Stage_value_module::Stage_Value_Predictor2 (integer,intent(in) L, integer,intent(in) ktime)
Definition at line 94 of file Stage_Value_module.f90.
References runge_kutta::alpha, control_variables::ustage, control_variables::uvec, and control_variables::uveco.
Referenced by Stage_Value_Predictor().
real(wp) Stage_value_module::xnorm (real(wp),dimension(:),intent(in) vec1, real(wp),dimension(:),intent(in) vec2)
Definition at line 130 of file Stage_Value_module.f90.
Referenced by test_cases().