Doxygen Fortran Example: unary_mod Module Reference
unary_mod Module Reference
Functions/Subroutines
subroutine submat (n, job, i1, i2, j1, j2, a, ja, ia, nr, nc, ao, jao, iao)
subroutine filter (n, job, drptol, a, ja, ia, b, jb, ib, len, ierr)
subroutine filterm (n, job, drop, a, ja, b, jb, len, ierr)
subroutine csort (n, a, ja, ia, iwork, values)
subroutine clean_CSR (nrow, ja, ia)
subroutine clncsr (job, value2, nrow, a, ja, ia, indu, iwk)
subroutine copmat (nrow, a, ja, ia, ao, jao, iao, ipos, job)
subroutine msrcop (nrow, a, ja, ao, jao, job)
double precision getelm (i, j, a, ja, ia, iadd, sorted)
subroutine getdia (nrow, ncol, job, a, ja, ia, len, diag, idiag, ioff)
subroutine transp (nrow, ncol, a, ja, ia, iwk, ierr)
subroutine getl (n, a, ja, ia, ao, jao, iao)
subroutine getu (n, a, ja, ia, ao, jao, iao)
subroutine levels (n, jal, ial, nlev, lev, ilev, levnum)
subroutine amask (nrow, ncol, a, ja, ia, jmask, imask, c, jc, ic, iw, nzmax, ierr)
subroutine rperm (nrow, a, ja, ia, ao, jao, iao, perm, job)
subroutine cperm (nrow, a, ja, ia, ao, jao, iao, perm, job)
subroutine dperm (nrow, a, ja, ia, ao, jao, iao, perm, qperm, job)
subroutine dperm1 (i1, i2, a, ja, ia, b, jb, ib, perm, ipos, job)
subroutine dperm2 (i1, i2, a, ja, ia, b, jb, ib, cperm, rperm, istart, ipos, job)
subroutine dmperm (nrow, a, ja, ao, jao, perm, job)
subroutine dvperm (n, x, perm)
subroutine ivperm (n, ix, perm)
subroutine retmx (n, a, ja, ia, dd)
subroutine diapos (n, ja, ia, idiag)
subroutine dscaldg (n, a, ja, ia, diag, job)
subroutine extbdg (n, a, ja, ia, bdiag, nblk, ao, jao, iao)
subroutine getbwd (n, a, ja, ia, ml, mu)
subroutine blkfnd (nrow, ja, ia, nblk)
subroutine blkchk (nrow, ja, ia, nblk, imsg)
subroutine infdia (n, ja, ia, ind, idiag)
subroutine amubdg (nrow, ncol, ncolb, ja, ia, jb, ib, ndegr, nnz, iw)
subroutine aplbdg (nrow, ncol, ja, ia, jb, ib, ndegr, nnz, iw)
subroutine rnrms (nrow, nrm, a, ja, ia, diag)
subroutine cnrms (nrow, nrm, a, ja, ia, diag)
subroutine roscal (nrow, job, nrm, a, ja, ia, diag, b, jb, ib, ierr)
subroutine coscal (nrow, job, nrm, a, ja, ia, diag, b, jb, ib, ierr)
subroutine addblk (nrowa, ncola, a, ja, ia, ipos, jpos, job, nrowb, ncolb, b, jb, ib, nrowc, ncolc, c, jc, ic, nzmx, ierr)
subroutine block_addblk (nb, nrowa, ncola, a, ja, ia, ipos, jpos, job, nrowb, ncolb, b, jb, ib, nrowc, ncolc, c, jc, ic, nzmx, ierr)
subroutine get1up (n, ja, ia, ju)
subroutine xtrows (i1, i2, a, ja, ia, ao, jao, iao, iperm, job)
subroutine csrkvstr (n, ia, ja, nr, kvstr)
subroutine csrkvstc (n, ia, ja, nc, kvstc, iwk)
subroutine kvstmerge (nr, kvstr, nc, kvstc, n, kvst)
subroutine amub (nrow, ncol, job, a, ja, ia, b, jb, ib, c, jc, ic, nzmax, iw, ierr)
subroutine a_sc_mu_b_bl (nrow, ncol, nb, a, ja, ia, b, jb, ib, c, jc, ic, nzmax, iw, ierr)
subroutine a_bl_mu_b_bl (nrow, ncol, nb, a, ja, ia, b, jb, ib, c, jc, ic, nzmax, iw, ierr)
subroutine a_bl_mu_b_sc (nrow, ncol, nb, a, ja, ia, b, jb, ib, c, jc, ic, nzmax, iw, ierr)
subroutine aplb (nrow, ncol, job, a, ja, ia, b, jb, ib, c, jc, ic, nzmax, iw, ierr)
subroutine aplb1 (nrow, ncol, job, a, ja, ia, b, jb, ib, c, jc, ic, nzmax, ierr)
subroutine a_bl_pl_b_bl1 (nrow, ncol, nblk, a, ja, ia, b, jb, ib, c, jc, ic, nzmax, ierr)
subroutine aplsb (nrow, ncol, a, ja, ia, s, b, jb, ib, c, jc, ic, nzmax, ierr)
subroutine aplsb1 (nrow, ncol, a, ja, ia, s, b, jb, ib, c, jc, ic, nzmax, ierr)
subroutine diamua (nrow, job, a, ja, ia, diag, b, jb, ib)
subroutine amudia (nrow, job, a, ja, ia, diag, b, jb, ib)
subroutine aplsca (nrow, a, ja, ia, scal, iw)
subroutine a_bl_pl_b_bl_scal (nrow, nb, a, ja, ia, scal, iw)
subroutine apldia (nrow, job, a, ja, ia, diag, b, jb, ib, iw)
subroutine a_bl_pl_b_bl_diag (nrow, nb, job, a, ja, ia, diag, b, jb, ib, iw)
subroutine qsortd (x, ind, n)
subroutine qsorti (IX, ind, n)
subroutine csrcsc (n, job, ipos, a, ja, ia, ao, jao, iao)
subroutine csort_block (block_size, n, a, ja, ia, iwork, values)
subroutine dvperm_block (block_size, n, x, perm)
subroutine a_bl_mu_x (block_size, n_row_blocks, x, y, a, ja, ia)
Function/Subroutine Documentation
subroutine unary_mod::a_bl_mu_b_bl (integer,intent(in) nrow, integer,intent(in) ncol, integer,intent(in) nb, real(wp),dimension(nb,nb,*),intent(in) a, integer,dimension(*),intent(in) ja, integer,dimension(nrow+1),intent(in) ia, real(wp),dimension(nb,nb,*),intent(in) b, integer,dimension(*),intent(in) jb, integer,dimension(*),intent(in) ib, real(wp),dimension(nb,nb,*),intent(out) c, integer,dimension(*),intent(out) jc, integer,dimension(*),intent(out) ic, integer,intent(in) nzmax, integer,dimension(*),intent(inout) iw, integer,intent(out) ierr)
Definition at line 3829 of file unary_mod.f90.
subroutine unary_mod::a_bl_mu_b_sc (integer,intent(in) nrow, integer,intent(in) ncol, integer,intent(in) nb, real(wp),dimension(nb,nb,*),intent(in) a, integer,dimension(*),intent(in) ja, integer,dimension(nrow+1),intent(in) ia, real(wp),dimension(*),intent(in) b, integer,dimension(*),intent(in) jb, integer,dimension(*),intent(in) ib, real(wp),dimension(nb,nb,*),intent(out) c, integer,dimension(*),intent(out) jc, integer,dimension(*),intent(out) ic, integer,intent(in) nzmax, integer,dimension(*),intent(inout) iw, integer,intent(out) ierr)
Definition at line 3933 of file unary_mod.f90.
subroutine unary_mod::a_bl_mu_x (integer block_size, integer n_row_blocks, real(wp),dimension(block_size*n_row_blocks) x, real(wp),dimension(block_size*n_row_blocks) y, real(wp),dimension(block_size,block_size,*) a, integer,dimension(*) ja, integer,dimension(*) ia)
Definition at line 6327 of file unary_mod.f90.
subroutine unary_mod::a_bl_pl_b_bl1 (integer,intent(in) nrow, integer,intent(in) ncol, integer,intent(in) nblk, real(wp),dimension(nblk,nblk,*),intent(in) a, integer,dimension(*),intent(in) ja, integer,dimension(nrow+1),intent(in) ia, real(wp),dimension(nblk,nblk,*),intent(in) b, integer,dimension(*),intent(in) jb, integer,dimension(nrow+1),intent(in) ib, real(wp),dimension(nblk,nblk,*),intent(inout) c, integer,dimension(*),intent(inout) jc, integer,dimension(nrow+1),intent(inout) ic, integer,intent(in) nzmax, integer,intent(out) ierr)
Definition at line 4333 of file unary_mod.f90.
subroutine unary_mod::a_bl_pl_b_bl_diag (integer,intent(in) nrow, integer,intent(in) nb, integer,intent(in) job, real(wp),dimension(nb,nb,*),intent(in) a, integer,dimension(*),intent(in) ja, integer,dimension(nrow+1),intent(in) ia, real(wp),dimension(nb,nb,nrow),intent(in) diag, real(wp),dimension(nb,nb,*),intent(inout) b, integer,dimension(*),intent(inout) jb, integer,dimension(nrow+1),intent(inout) ib, integer,dimension(*),intent(inout) iw)
Definition at line 5426 of file unary_mod.f90.
References diapos().
subroutine unary_mod::a_bl_pl_b_bl_scal (integer,intent(in) nrow, integer,intent(in) nb, real(wp),dimension(nb,nb,*),intent(inout) a, integer,dimension(*),intent(inout) ja, integer,dimension(nrow+1),intent(inout) ia, real(wp),intent(in) scal, integer,dimension(*),intent(inout) iw)
Definition at line 5183 of file unary_mod.f90.
References diapos().
subroutine unary_mod::a_sc_mu_b_bl (integer,intent(in) nrow, integer,intent(in) ncol, integer,intent(in) nb, real(wp),dimension(*),intent(in) a, integer,dimension(*),intent(in) ja, integer,dimension(nrow+1),intent(in) ia, real(wp),dimension(nb,nb,*),intent(in) b, integer,dimension(*),intent(in) jb, integer,dimension(*),intent(in) ib, real(wp),dimension(nb,nb,*),intent(out) c, integer,dimension(*),intent(out) jc, integer,dimension(*),intent(out) ic, integer,intent(in) nzmax, integer,dimension(*),intent(inout) iw, integer,intent(out) ierr)
Definition at line 3724 of file unary_mod.f90.
subroutine unary_mod::addblk (integer nrowa, integer ncola, real(wp),dimension(1:*) a, integer,dimension(1:*) ja, integer,dimension(1:*) ia, integer ipos, integer jpos, integer job, integer nrowb, integer ncolb, real(wp),dimension(1:*) b, integer,dimension(1:*) jb, integer,dimension(1:*) ib, integer nrowc, integer ncolc, real(wp),dimension(1:*) c, integer,dimension(1:*) jc, integer,dimension(1:*) ic, integer nzmx, integer ierr) [private]
Definition at line 3040 of file unary_mod.f90.
subroutine unary_mod::amask (integer nrow, integer ncol, real(wp),dimension(*) a, integer,dimension(*) ja, integer,dimension(nrow+1) ia, integer,dimension(*) jmask, integer,dimension(nrow+1) imask, real(wp),dimension(*) c, integer,dimension(*) jc, integer,dimension(nrow+1) ic, logical,dimension(ncol) iw, integer nzmax, integer ierr) [private]
Definition at line 1391 of file unary_mod.f90.
subroutine unary_mod::amub (integer nrow, integer ncol, integer job, real(wp),dimension(*) a, integer,dimension(*) ja, integer,dimension(nrow+1) ia, real(wp),dimension(*) b, integer,dimension(*) jb, integer,dimension(ncol+1) ib, real(wp),dimension(nzmax) c, integer,dimension(nzmax) jc, integer,dimension(ncol+1) ic, integer nzmax, integer,dimension(ncol) iw, integer ierr)
Definition at line 3579 of file unary_mod.f90.
subroutine unary_mod::amubdg (integer nrow, integer ncol, integer ncolb, integer,dimension(*) ja, integer,dimension(nrow+1) ia, integer,dimension(*) jb, integer,dimension(ncol+1) ib, integer,dimension(nrow) ndegr, integer nnz, integer,dimension(ncolb) iw)
Definition at line 2577 of file unary_mod.f90.
subroutine unary_mod::amudia (integer nrow, integer job, real(wp),dimension(*) a, integer,dimension(*) ja, integer,dimension(nrow+1) ia, real(wp),dimension(nrow) diag, real(wp),dimension(*) b, integer,dimension(*) jb, integer,dimension(nrow+1) ib)
Definition at line 5022 of file unary_mod.f90.
Referenced by Burgers_Module::Build_Jac(), and coscal().
subroutine unary_mod::aplb (integer nrow, integer ncol, integer job, real(wp),dimension(*) a, integer,dimension(*) ja, integer,dimension(nrow+1) ia, real(wp),dimension(*) b, integer,dimension(*) jb, integer,dimension(nrow+1) ib, real(wp),dimension(*) c, integer,dimension(*) jc, integer,dimension(nrow+1) ic, integer nzmax, integer,dimension(ncol) iw, integer ierr)
Definition at line 4036 of file unary_mod.f90.
Referenced by Boscarino31_Mod::Bosc_dUdt(), Boscarino31_Mod::Boscarino31(), and Burgers_Module::Build_Jac().
subroutine unary_mod::aplb1 (integer,intent(in) nrow, integer,intent(in) ncol, integer,intent(in) job, real(wp),dimension(*),intent(in) a, integer,dimension(*),intent(in) ja, integer,dimension(nrow+1),intent(in) ia, real(wp),dimension(*),intent(in) b, integer,dimension(*),intent(in) jb, integer,dimension(nrow+1),intent(in) ib, real(wp),dimension(*),intent(inout) c, integer,dimension(*),intent(inout) jc, integer,dimension(nrow+1),intent(inout) ic, integer,intent(inout) nzmax, integer,intent(out) ierr)
Definition at line 4182 of file unary_mod.f90.
subroutine unary_mod::aplbdg (integer nrow, integer ncol, integer,dimension(*) ja, integer,dimension(nrow+1) ia, integer,dimension(*) jb, integer,dimension(nrow+1) ib, integer,dimension(nrow) ndegr, integer nnz, integer,dimension(ncol) iw)
Definition at line 2697 of file unary_mod.f90.
subroutine unary_mod::apldia (integer nrow, integer job, real(wp),dimension(*) a, integer,dimension(*) ja, integer,dimension(nrow+1) ia, real(wp),dimension(nrow) diag, real(wp),dimension(*) b, integer,dimension(*) jb, integer,dimension(nrow+1) ib, integer,dimension(*) iw)
Definition at line 5301 of file unary_mod.f90.
References diapos().
Referenced by Burgers_Module::Build_Jac().
subroutine unary_mod::aplsb (integer nrow, integer ncol, real(wp),dimension(*) a, integer,dimension(*) ja, integer,dimension(nrow+1) ia, real(wp) s, real(wp),dimension(*) b, integer,dimension(*) jb, integer,dimension(nrow+1) ib, real(wp),dimension(*) c, integer,dimension(*) jc, integer,dimension(nrow+1) ic, integer nzmax, integer ierr) [private]
Definition at line 4473 of file unary_mod.f90.
subroutine unary_mod::aplsb1 (integer nrow, integer ncol, real(wp),dimension(*) a, integer,dimension(*) ja, integer,dimension(nrow+1) ia, real(wp) s, real(wp),dimension(*) b, integer,dimension(*) jb, integer,dimension(nrow+1) ib, real(wp),dimension(*) c, integer,dimension(*) jc, integer,dimension(nrow+1) ic, integer nzmax, integer ierr) [private]
Definition at line 4587 of file unary_mod.f90.
subroutine unary_mod::aplsca (integer nrow, real(wp),dimension(*) a, integer,dimension(*) ja, integer,dimension(nrow+1) ia, real(wp) scal, integer,dimension(*) iw)
Definition at line 5083 of file unary_mod.f90.
References diapos().
Referenced by Boscarino31_Mod::Bosc_Jac(), and Burgers_Module::Build_Jac().
subroutine unary_mod::blkchk (integer nrow, integer,dimension(*) ja, integer,dimension(nrow+1) ia, integer nblk, integer imsg) [private]
Definition at line 2427 of file unary_mod.f90.
Referenced by blkfnd().
subroutine unary_mod::blkfnd (integer nrow, integer,dimension(*) ja, integer,dimension(nrow+1) ia, integer nblk) [private]
Definition at line 2342 of file unary_mod.f90.
References blkchk().
subroutine unary_mod::block_addblk (integer,intent(in) nb, integer,intent(in) nrowa, integer,intent(in) ncola, real(wp),dimension(nb,nb,*),intent(in) a, integer,dimension(*),intent(in) ja, integer,dimension(*),intent(in) ia, integer,intent(in) ipos, integer,intent(in) jpos, integer,intent(in) job, integer,intent(in) nrowb, integer,intent(in) ncolb, real(wp),dimension(nb,nb,*),intent(in) b, integer,dimension(*),intent(in) jb, integer,dimension(*),intent(in) ib, integer,intent(inout) nrowc, integer,intent(inout) ncolc, real(wp),dimension(nb,nb,*),intent(inout) c, integer,dimension(*),intent(inout) jc, integer,dimension(*),intent(inout) ic, integer,intent(in) nzmx, integer,intent(out) ierr) [private]
Definition at line 3161 of file unary_mod.f90.
subroutine unary_mod::clean_CSR (integer,intent(in) nrow, integer,dimension(:),intent(inout) ja, integer,dimension(nrow+1),intent(inout) ia)
Definition at line 493 of file unary_mod.f90.
subroutine unary_mod::clncsr (integer job, integer value2, integer nrow, real(wp),dimension(*) a, integer,dimension(*) ja, integer,dimension(nrow+1) ia, integer,dimension(nrow) indu, integer,dimension(nrow+1) iwk)
Definition at line 592 of file unary_mod.f90.
subroutine unary_mod::cnrms (integer nrow, integer nrm, real(wp),dimension(*) a, integer,dimension(*) ja, integer,dimension(nrow+1) ia, real(wp),dimension(nrow) diag) [private]
Definition at line 2869 of file unary_mod.f90.
Referenced by coscal().
subroutine unary_mod::copmat (integer nrow, real(wp),dimension(*) a, integer,dimension(*) ja, integer,dimension(*) ia, real(wp),dimension(*) ao, integer,dimension(*) jao, integer,dimension(*) iao, integer ipos, integer job) [private]
Definition at line 757 of file unary_mod.f90.
subroutine unary_mod::coscal (integer nrow, integer job, integer nrm, real(wp),dimension(*) a, integer,dimension(*) ja, integer,dimension(nrow+1) ia, real(wp),dimension(nrow) diag, real(wp),dimension(*) b, integer,dimension(*) jb, integer,dimension(nrow+1) ib, integer ierr) [private]
Definition at line 2980 of file unary_mod.f90.
References amudia(), and cnrms().
subroutine unary_mod::cperm (integer nrow, real(wp),dimension(*) a, integer,dimension(*) ja, integer,dimension(nrow+1) ia, real(wp),dimension(*) ao, integer,dimension(*) jao, integer,dimension(nrow+1) iao, integer,dimension(*) perm, integer job)
Definition at line 1558 of file unary_mod.f90.
Referenced by dperm().
subroutine unary_mod::csort (integer n, real(wp),dimension(*) a, integer,dimension(*) ja, integer,dimension(n+1) ia, integer,dimension(*) iwork, logical values)
Definition at line 355 of file unary_mod.f90.
References dvperm(), and ivperm().
Referenced by Boscarino31_Mod::Bosc_dUdt().
subroutine unary_mod::csort_block (integer block_size, integer n, real(wp),dimension(block_size,block_size,*) a, integer,dimension(*) ja, integer,dimension(n+1) ia, integer,dimension(*) iwork, logical values)
Definition at line 6081 of file unary_mod.f90.
References dvperm_block(), and ivperm().
subroutine unary_mod::csrcsc (integer n, integer job, integer ipos, real (wp),dimension(*) a, integer,dimension(*) ja, integer,dimension(n+1) ia, real (wp),dimension(*) ao, integer,dimension(*) jao, integer,dimension(n+1) iao)
Definition at line 5976 of file unary_mod.f90.
subroutine unary_mod::csrkvstc (integer n, integer,dimension(n+1) ia, integer,dimension(*) ja, integer nc, integer,dimension(*) kvstc, integer,dimension(*) iwk) [private]
Definition at line 3459 of file unary_mod.f90.
subroutine unary_mod::csrkvstr (integer n, integer,dimension(n+1) ia, integer,dimension(*) ja, integer nr, integer,dimension(*) kvstr) [private]
Definition at line 3409 of file unary_mod.f90.
subroutine unary_mod::diamua (integer nrow, integer job, real(wp),dimension(*) a, integer,dimension(*) ja, integer,dimension(nrow+1) ia, real(wp),dimension(nrow) diag, real(wp),dimension(*) b, integer,dimension(*) jb, integer,dimension(nrow+1) ib)
Definition at line 4963 of file unary_mod.f90.
Referenced by Burgers_Module::Build_Jac(), and roscal().
subroutine unary_mod::diapos (integer n, integer,dimension(*) ja, integer,dimension(n+1) ia, integer,dimension(n) idiag) [private]
Definition at line 2140 of file unary_mod.f90.
Referenced by a_bl_pl_b_bl_diag(), a_bl_pl_b_bl_scal(), apldia(), and aplsca().
subroutine unary_mod::dmperm (integer nrow, real(wp),dimension(*) a, integer,dimension(*) ja, real(wp),dimension(*) ao, integer,dimension(*) jao, integer,dimension(nrow) perm, integer job) [private]
Definition at line 1853 of file unary_mod.f90.
References dperm().
subroutine unary_mod::dperm (integer nrow, real(wp),dimension(*) a, integer,dimension(*) ja, integer,dimension(nrow+1) ia, real(wp),dimension(*) ao, integer,dimension(*) jao, integer,dimension(nrow+1) iao, integer,dimension(nrow) perm, integer,dimension(*) qperm, integer job)
Definition at line 1626 of file unary_mod.f90.
References cperm(), and rperm().
Referenced by Boscarino31_Mod::Bosc_dUdt(), and dmperm().
subroutine unary_mod::dperm1 (integer i1, integer i2, real(wp),dimension(*) a, integer,dimension(*) ja, integer,dimension(*) ia, real(wp),dimension(*) b, integer,dimension(*) jb, integer,dimension(*) ib, integer,dimension(*) perm, integer ipos, integer job) [private]
Definition at line 1702 of file unary_mod.f90.
subroutine unary_mod::dperm2 (integer i1, integer i2, real(wp),dimension(*) a, integer,dimension(*) ja, integer,dimension(*) ia, real(wp),dimension(*) b, integer,dimension(*) jb, integer,dimension(*) ib, integer,dimension(*) cperm, integer,dimension(*) rperm, integer istart, integer ipos, integer job) [private]
Definition at line 1762 of file unary_mod.f90.
subroutine unary_mod::dscaldg (integer n, real(wp),dimension(*) a, integer,dimension(*) ja, integer,dimension(*) ia, real(wp),dimension(*) diag, integer job) [private]
Definition at line 2181 of file unary_mod.f90.
References retmx().
subroutine unary_mod::dvperm (integer n, real(wp),dimension(n) x, integer,dimension(n) perm) [private]
Definition at line 1910 of file unary_mod.f90.
Referenced by csort().
subroutine unary_mod::dvperm_block (integer block_size, integer n, real(wp),dimension(block_size,block_size,n) x, integer,dimension(n) perm) [private]
Definition at line 6222 of file unary_mod.f90.
Referenced by csort_block().
subroutine unary_mod::extbdg (integer n, real(wp),dimension(*) a, integer,dimension(*) ja, integer,dimension(*) ia, real(wp),dimension(*) bdiag, integer nblk, real(wp),dimension(*) ao, integer,dimension(*) jao, integer,dimension(*) iao) [private]
Definition at line 2228 of file unary_mod.f90.
subroutine unary_mod::filter (integer n, integer job, real(wp) drptol, real(wp),dimension(*) a, integer,dimension(*) ja, integer,dimension(*) ia, real(wp),dimension(*) b, integer,dimension(*) jb, integer,dimension(*) ib, integer len, integer ierr) [private]
Definition at line 176 of file unary_mod.f90.
subroutine unary_mod::filterm (integer n, integer job, real(wp) drop, real(wp),dimension(*) a, integer,dimension(*) ja, real(wp),dimension(*) b, integer,dimension(*) jb, integer len, integer ierr) [private]
Definition at line 268 of file unary_mod.f90.
subroutine unary_mod::get1up (integer n, integer,dimension(*) ja, integer,dimension(*) ia, integer,dimension(*) ju) [private]
Definition at line 3297 of file unary_mod.f90.
subroutine unary_mod::getbwd (integer n, real(wp),dimension(*) a, integer,dimension(*) ja, integer,dimension(n+1) ia, integer ml, integer mu) [private]
Definition at line 2298 of file unary_mod.f90.
subroutine unary_mod::getdia (integer nrow, integer ncol, integer job, real(wp),dimension(*) a, integer,dimension(*) ja, integer,dimension(*) ia, integer len, real(wp),dimension(*) diag, integer,dimension(*) idiag, integer ioff) [private]
Definition at line 950 of file unary_mod.f90.
double precision unary_mod::getelm (integer i, integer j, double precision,dimension(*) a, integer,dimension(*) ja, integer,dimension(*) ia, integer iadd, logical sorted) [private]
Definition at line 847 of file unary_mod.f90.
subroutine unary_mod::getl (integer n, real(wp),dimension(*) a, integer,dimension(*) ja, integer,dimension(*) ia, real(wp),dimension(*) ao, integer,dimension(*) jao, integer,dimension(*) iao) [private]
Definition at line 1198 of file unary_mod.f90.
subroutine unary_mod::getu (integer n, real(wp),dimension(*) a, integer,dimension(*) ja, integer,dimension(*) ia, real(wp),dimension(*) ao, integer,dimension(*) jao, integer,dimension(*) iao) [private]
Definition at line 1258 of file unary_mod.f90.
subroutine unary_mod::infdia (integer n, integer,dimension(*) ja, integer,dimension(*) ia, integer,dimension(*) ind, integer idiag) [private]
Definition at line 2525 of file unary_mod.f90.
subroutine unary_mod::ivperm (integer n, integer,dimension(n) ix, integer,dimension(n) perm) [private]
Definition at line 2014 of file unary_mod.f90.
Referenced by csort(), and csort_block().
subroutine unary_mod::kvstmerge (integer nr, integer,dimension(nr+1) kvstr, integer nc, integer,dimension(nc+1) kvstc, integer n, integer,dimension(*) kvst) [private]
Definition at line 3525 of file unary_mod.f90.
subroutine unary_mod::levels (integer n, integer,dimension(*) jal, integer,dimension(*) ial, integer nlev, integer,dimension(*) lev, integer,dimension(*) ilev, integer,dimension(*) levnum) [private]
Definition at line 1313 of file unary_mod.f90.
subroutine unary_mod::msrcop (integer nrow, real(wp),dimension(*) a, integer,dimension(*) ja, real(wp),dimension(*) ao, integer,dimension(*) jao, integer job) [private]
Definition at line 805 of file unary_mod.f90.
subroutine unary_mod::qsortd (real(wp),dimension(:),intent(in) x, INTEGER,dimension(:),intent(out) ind, INTEGER,intent(in) n)
Definition at line 5567 of file unary_mod.f90.
subroutine unary_mod::qsorti (Integer,dimension(:),intent(in) IX, INTEGER,dimension(:),intent(out) ind, INTEGER,intent(in) n)
Definition at line 5771 of file unary_mod.f90.
subroutine unary_mod::retmx (integer n, real(wp),dimension(*) a, integer,dimension(*) ja, integer,dimension(*) ia, real(wp),dimension(*) dd) [private]
Definition at line 2088 of file unary_mod.f90.
Referenced by dscaldg().
subroutine unary_mod::rnrms (integer nrow, integer nrm, real(wp),dimension(*) a, integer,dimension(*) ja, integer,dimension(nrow+1) ia, real(wp),dimension(nrow) diag) [private]
Definition at line 2815 of file unary_mod.f90.
Referenced by roscal().
subroutine unary_mod::roscal (integer nrow, integer job, integer nrm, real(wp),dimension(*) a, integer,dimension(*) ja, integer,dimension(nrow+1) ia, real(wp),dimension(nrow) diag, real(wp),dimension(*) b, integer,dimension(*) jb, integer,dimension(nrow+1) ib, integer ierr) [private]
Definition at line 2922 of file unary_mod.f90.
References diamua(), and rnrms().
subroutine unary_mod::rperm (integer nrow, real(wp),dimension(*) a, integer,dimension(*) ja, integer,dimension(nrow+1) ia, real(wp),dimension(*) ao, integer,dimension(*) jao, integer,dimension(nrow+1) iao, integer,dimension(nrow) perm, integer job)
Definition at line 1483 of file unary_mod.f90.
Referenced by dperm().
subroutine unary_mod::submat (integer n, integer job, integer i1, integer i2, integer j1, integer j2, real(wp),dimension(*) a, integer,dimension(*) ja, integer,dimension(*) ia, integer nr, integer nc, real(wp),dimension(*) ao, integer,dimension(*) jao, integer,dimension(*) iao)
Definition at line 102 of file unary_mod.f90.
subroutine unary_mod::transp (integer nrow, integer ncol, real(wp),dimension(*) a, integer,dimension(*) ja, integer,dimension(*) ia, integer,dimension(*) iwk, integer ierr)
Definition at line 1060 of file unary_mod.f90.
subroutine unary_mod::xtrows (integer i1, integer i2, real(wp),dimension(*) a, integer,dimension(*) ja, integer,dimension(*) ia, real(wp),dimension(*) ao, integer,dimension(*) jao, integer,dimension(*) iao, integer,dimension(*) iperm, integer job) [private]
Definition at line 3342 of file unary_mod.f90.